/*
Copyright 2013, KISS UI Library v0.7.2
MIT Licensed
build time: Jan 25 16:35
*/(function(d){trace=function(b){window.console.log(b)};Sketchpad=function(b,a){this.sketchpad=b;a=d.extend({height:400,width:500,colors:"#000000,#FF0000,#80FF00,#00FFFF,#808080,#FF8000,#408080,#8000FF,#CCCC00".split(","),size:[1,3,5,7],background:"#fff",image:void 0,grid:!1,layout:"",plugins:["pen","line","text","eraser","clear"]},a);this.init(a)};Sketchpad.plugins={};Sketchpad.plugin=function(b,a){return d.each(b.split(","),function(b,g){Sketchpad.plugins[g]=a})};Sketchpad.prototype={style:{},plugins:{},
action:"pen",state:"normal",data:[],text:[],init:function(b){var a=this;a.options=b;d(a.sketchpad).css({height:b.height,width:b.width});a.canvas=a.tempLayer=document.getElementById("tempLayer");a.backgroundLayer=document.getElementById("backgroundLayer");a.graphicsLayer=document.getElementById("graphicsLayer");a.textLayer=document.getElementById("textLayer");a.webLayer=document.getElementById("webLayer");a.layers=[a.tempLayer,a.backgroundLayer,a.graphicsLayer,a.textLayer,a.webLayer];d.each(a.layers,
function(){this.height=b.height;this.width=b.width});a.leftbar=d("#sketchpad-toolbar");a.attrbar=d("#sketchpad-attribute-bar");a.leftbar.height(b.height);a.toolbar=new a._toolbar(a,b);a.cmd=new Sketchpad.cmd(a);d(a.canvas).on("mousedown touchstart",function(b){a.active&&(b.preventDefault(),b.stopPropagation());a.cmd[a.action]&&(a.cmd[a.action](b,"start"),a.active=!0)}).on("mousemove touchmove",function(b){if(a.active&&a.cmd[a.action])a.cmd[a.action](b,"run")}).on("mouseup touchend",function(b){a.active&&
a.cmd[a.action]&&(a.cmd[a.action](b,"stop"),a.active=!1)});a.toolbar.active(a.action)},_toolbar:function(b,a){var c=this;c.sketchpad=b;d.each(a.plugins,function(a,c){var d=Sketchpad.plugins[c];d&&(d=d(c,b),!1!==d.support&&(d.toolbar&&(d.toolbar=d.toolbar.attr("unselectable","on"),b.leftbar.append(d.toolbar),d.attrbar&&b.attrbar.append(d.attrbar)),b.plugins[c]=d))});c.active=function(a){b.action=a;c.sketchpad.leftbar.find("span.active").removeClass("active");c.sketchpad.leftbar.find("span."+a).addClass("active");
a=b.plugins[a];a.attrbar&&(b.attrbar.find("div.active").removeClass("active").hide(),a.attrbar.addClass("active").show().trigger("active"))};c.enable=function(a){this.editor.data.plugins[a].toolbar.removeClass("disabled")};c.disable=function(a){this.editor.data.plugins[a].toolbar.addClass("disabled")};c.disableAll=function(){}}};Sketchpad.cmd=function(b){this.sketchpad=b;this.context=b.canvas.getContext("2d");this.grapcontext=b.graphicsLayer.getContext("2d")};Sketchpad.cmd.prototype={position:function(b){window.console.log(b);
var a,c;b.offsetX?(a=b.offsetX,c=b.offsetY):b.layerX?(a=b.layerX,c=b.layerY):(b=b.originalEvent,b.layerX&&(a=b.layerX,c=b.layerY));return{x:a,y:c}},point:function(b){var a=this.context,c=this.sketchpad.data;a.beginPath();var d=c[c.length-1].value;a.moveTo(d.x,d.y);a.lineTo(b.x,b.y);a.closePath();a.stroke();c.push({action:this.sketchpad.action,name:"move",value:b})},draw:function(){var b=this.sketchpad.canvas;if(d.browser.msie&&9>d.browser.version){var a=new Image;a.src=b.toDataURL("image/png");this.grapcontext.drawImage(a,
0,0)}else this.grapcontext.drawImage(b,0,0);this.context.clearRect(0,0,b.width,b.height)},move:function(b,a){a&&(this.context.lineJoin="round",this.context.lineWidth=3,this.point(b))},style:function(b,a){var c=this.context;this.sketchpad.style[b]=a;c.save();c[b]=a},clear:function(b){void 0==b&&(b=!0);var a=this.sketchpad;this.context.clearRect(0,0,a.canvas.width,a.canvas.height);this.grapcontext.clearRect(0,0,a.canvas.width,a.canvas.height);b&&d(a.sketchpad).find("div").remove()},save:function(){},
getImageData:function(b){var a=this,c=a.sketchpad.text;a.grapcontext.font="14px Helvetica, Tahoma, Arial, sans-serif";d.each(c,function(){a.grapcontext.fillStyle=this.fillStyle;a.grapcontext.fillText(this.text,this.x,this.y)});return this.sketchpad.graphicsLayer.toDataURL(b)},undo:function(){this.context.restore()},eraser:function(b,a){var c=this,d=c.grapcontext,e=c.sketchpad.data,f=c.position(b);({start:function(){e.push({action:c.sketchpad.action,name:"eraser-start",value:f})},run:function(){d.globalCompositeOperation=
"destination-out";d.beginPath();d.arc(f.x,f.y,20,0,2*Math.PI);d.strokeStyle="rgba(250,250,250,0)";d.fill();d.globalCompositeOperation="source-over"},stop:function(){e.push({action:c.sketchpad.action,name:"eraser-end",value:f})}})[a]()},pen:function(b,a){var c=this,d=c.context,e=c.sketchpad.data;({start:function(){d.beginPath();e.push({action:c.sketchpad.action,name:"start",value:c.position(b)})},run:function(){c.move(c.position(b),!0)},stop:function(){d.stroke();c.draw()}})[a]()},line:function(b,
a){var c=this,d=c.context,e=c.sketchpad.data,f=this.sketchpad.canvas,h=c.position(b),i={start:function(){e.push({action:c.sketchpad.action,name:"start",value:c.position(b)})},run:function(a){a||(a=h);var b=e[e.length-1].value;d.clearRect(0,0,f.width,f.height);d.beginPath();d.moveTo(b.x,b.y);d.lineTo(a.x,a.y);d.stroke();d.closePath()},stop:function(){i.run(h);c.draw();e.push({action:c.sketchpad.action,name:"end",value:h})}};i[a]()},text:function(b,a){var c=this,g=c.context,e=this.sketchpad.canvas,
f=c.position(b),h={start:function(){var a=d('<div contentEditable="true"  class="text" style="color:'+g.strokeStyle+'"></div>');a.css({position:"absolute",top:f.y,left:f.x});d(e).after(a);a.focus(function(){d(this).addClass("active")}).blur(function(){h.run(this);d(this).removeClass("active")}).keydown(function(a){if(13==a.which){var b=window.getSelection?window.getSelection():document.selection,b=b.createRange?b.createRange():b.getRangeAt(0);window.getSelection||(b.pasteHTML("<br>"),b.collapse(!1),
b.select(),a.preventDefault())}});setTimeout(function(){a.focus()},100)},run:function(a){var b=d(a).text();""==d.trim(b)?d(a).remove():c.sketchpad.text.push({text:b,x:f.x+6,y:f.y+16,fillStyle:g.strokeStyle});h.stop()},stop:function(){c.sketchpad.active=!1}};h[a]()}};var j={pen:"\u94c5\u7b14\u5de5\u5177",line:"\u76f4\u7ebf\u5de5\u5177",text:"\u6587\u5b57\u5de5\u5177",eraser:"\u6a61\u76ae\u64e6",clear:"\u6e05\u9664",save:"\u4fdd\u5b58"};Sketchpad.plugin("pen,line,text,eraser",function(b,a){var c={};"eraser"==b&&(c.support=!(d.browser.msie&&9>d.browser.version));c.attrbar=d('<div class="sketchpad-attrbar" name="'+
b+'"></div>');c.toolbar=d('<span   class="'+b+'"  title="'+j[b]+'"></span>').click(function(){a.toolbar.active(b)});if(-1!=d.inArray(b,["pen","line","text"])){var g=['<div class="sketchpad-color">'];d.each(a.options.colors,function(){g.push('<span style="background:'+this+'" data-color="'+this+'"></span>')});g.push("</div>");var e=d(g.join(""));e.find("span").click(function(){var b=d(this);a.cmd.style("strokeStyle",b.data("color"));e.find("span.active").removeClass("active");b.addClass("active")}).eq(0).addClass("active");
c.attrbar.on("active",function(){var b=e.find("span.active:first");a.cmd.style("strokeStyle",b.data("color"))});c.attrbar.append(e)}return c});Sketchpad.plugin("save,clear",function(b,a){var c={};c.toolbar=d('<span   class="'+b+'"  title="'+j[b]+'"></span>').click(function(){a.cmd[b]()});return c});d.fn.sketchpad=function(b){return this.each(function(){this.sketchpad||(this.sketchpad=new Sketchpad(this,b));return this})}})(jQuery);
