/*
Copyright 2012, KISS UI Library v0.7.1
MIT Licensed
build time: May 29 15:32
*/"undefined"!==typeof dojo?dojo.provide("org.cometd"):(this.org=this.org||{},org.cometd={});org.cometd.JSON={};org.cometd.JSON.toJSON=org.cometd.JSON.fromJSON=function(){throw"Abstract";};org.cometd.Utils={};org.cometd.Utils.isString=function(b){return b===void 0||b===null?false:typeof b==="string"||b instanceof String};org.cometd.Utils.isArray=function(b){return b===void 0||b===null?false:b instanceof Array};org.cometd.Utils.inArray=function(b,g){for(var c=0;c<g.length;++c)if(b===g[c])return c;return-1};
org.cometd.Utils.setTimeout=function(b,g,c){return window.setTimeout(function(){try{g()}catch(c){b._debug("Exception invoking timed function",g,c)}},c)};org.cometd.Utils.clearTimeout=function(b){window.clearTimeout(b)};
org.cometd.TransportRegistry=function(){var b=[],g={};this.getTransportTypes=function(){return b.slice(0)};this.findTransportTypes=function(c,i,d){for(var a=[],h=0;h<b.length;++h){var j=b[h];g[j].accept(c,i,d)===true&&a.push(j)}return a};this.negotiateTransport=function(c,i,d,a){for(var h=0;h<b.length;++h)for(var j=b[h],m=0;m<c.length;++m)if(j===c[m]){var k=g[j];if(k.accept(i,d,a)===true)return k}return null};this.add=function(c,i,d){for(var a=false,h=0;h<b.length;++h)if(b[h]===c){a=true;break}if(!a){typeof d!==
"number"?b.push(c):b.splice(d,0,c);g[c]=i}return!a};this.find=function(c){for(var i=0;i<b.length;++i)if(b[i]===c)return g[c];return null};this.remove=function(c){for(var i=0;i<b.length;++i)if(b[i]===c){b.splice(i,1);i=g[c];delete g[c];return i}return null};this.clear=function(){b=[];g={}};this.reset=function(){for(var c=0;c<b.length;++c)g[b[c]].reset()}};
org.cometd.Transport=function(){var b,g;this.registered=function(c,i){b=c;g=i};this.unregistered=function(){g=b=null};this._debug=function(){g._debug.apply(g,arguments)};this._mixin=function(){return g._mixin.apply(g,arguments)};this.getConfiguration=function(){return g.getConfiguration()};this.getAdvice=function(){return g.getAdvice()};this.setTimeout=function(c,b){return org.cometd.Utils.setTimeout(g,c,b)};this.clearTimeout=function(c){org.cometd.Utils.clearTimeout(c)};this.convertToMessages=function(c){if(org.cometd.Utils.isString(c))try{return org.cometd.JSON.fromJSON(c)}catch(b){this._debug("Could not convert to JSON the following string",
'"'+c+'"');throw b;}if(org.cometd.Utils.isArray(c))return c;if(c===void 0||c===null)return[];if(c instanceof Object)return[c];throw"Conversion Error "+c+", typeof "+typeof c;};this.accept=function(){throw"Abstract";};this.getType=function(){return b};this.send=function(){throw"Abstract";};this.reset=function(){this._debug("Transport",b,"reset")};this.abort=function(){this._debug("Transport",b,"aborted")};this.toString=function(){return this.getType()}};
org.cometd.Transport.derive=function(b){function g(){}g.prototype=b;return new g};
org.cometd.RequestTransport=function(){function b(f){for(;k.length>0;){var a=k[0],c=a[0],a=a[1];if(c.url===f.url&&c.sync===f.sync){k.shift();f.messages=f.messages.concat(c.messages);this._debug("Coalesced",c.messages.length,"messages from request",a.id)}else break}}function g(f,a){this.transportSend(f,a);a.expired=false;if(!f.sync){var c=this.getConfiguration().maxNetworkDelay,b=c;a.metaConnect===true&&(b=b+this.getAdvice().timeout);this._debug("Transport",this.getType(),"waiting at most",b,"ms for the response, maxNetworkDelay",
c);var d=this;a.timeout=this.setTimeout(function(){a.expired=true;a.xhr&&a.xhr.abort();var c="Request "+a.id+" of transport "+d.getType()+" exceeded "+b+" ms max network delay";d._debug(c);d.complete(a,false,a.metaConnect);f.onFailure(a.xhr,f.messages,"timeout",c)},b)}}function c(f){var a=++h,c={id:a,metaConnect:false};if(m.length<this.getConfiguration().maxConnections-1){m.push(c);g.call(this,f,c)}else{this._debug("Transport",this.getType(),"queueing request",a,"envelope",f);k.push([f,c])}}function i(a,
d){var g=org.cometd.Utils.inArray(a,m);g>=0&&m.splice(g,1);if(k.length>0){var g=k.shift(),i=g[0],h=g[1];this._debug("Transport dequeued request",h.id);if(d){this.getConfiguration().autoBatch&&b.call(this,i);c.call(this,i);this._debug("Transport completed request",a.id,i)}else{var F=this;this.setTimeout(function(){F.complete(h,false,h.metaConnect);i.onFailure(h.xhr,i.messages,"error","Previous request failed")},0)}}}var d=new org.cometd.Transport,a=org.cometd.Transport.derive(d),h=0,j=null,m=[],k=
[];a.complete=function(a,c,b){if(b){a=a.id;this._debug("Transport",this.getType(),"metaConnect complete, request",a);if(j!==null&&j.id!==a)throw"Longpoll request mismatch, completing request "+a;j=null}else i.call(this,a,c)};a.transportSend=function(){throw"Abstract";};a.transportSuccess=function(a,c,b){if(!c.expired){this.clearTimeout(c.timeout);this.complete(c,true,c.metaConnect);if(b&&b.length>0)a.onSuccess(b);else a.onFailure(c.xhr,a.messages,"Empty HTTP response")}};a.transportFailure=function(a,
c,b,d){if(!c.expired){this.clearTimeout(c.timeout);this.complete(c,false,c.metaConnect);a.onFailure(c.xhr,a.messages,b,d)}};a.send=function(a,b){if(b){if(j!==null)throw"Concurrent metaConnect requests not allowed, request id="+j.id+" not yet completed";var d=++h;this._debug("Transport",this.getType(),"metaConnect send, request",d,"envelope",a);d={id:d,metaConnect:true};g.call(this,a,d);j=d}else c.call(this,a)};a.abort=function(){d.abort();for(var a=0;a<m.length;++a){var c=m[a];this._debug("Aborting request",
c);c.xhr&&c.xhr.abort()}if(j){this._debug("Aborting metaConnect request",j);j.xhr&&j.xhr.abort()}this.reset()};a.reset=function(){d.reset();j=null;m=[];k=[]};return a};
org.cometd.LongPollingTransport=function(){var b=new org.cometd.RequestTransport,g=org.cometd.Transport.derive(b),c=true;g.accept=function(b,d){return c||!d};g.xhrSend=function(){throw"Abstract";};g.transportSend=function(b,d){this._debug("Transport",this.getType(),"sending request",d.id,"envelope",b);var a=this;try{var g=true;d.xhr=this.xhrSend({transport:this,url:b.url,sync:b.sync,headers:this.getConfiguration().requestHeaders,body:org.cometd.JSON.toJSON(b.messages),onSuccess:function(g){a._debug("Transport",
a.getType(),"received response",g);var h=false;try{var f=a.convertToMessages(g);if(f.length===0){c=false;a.transportFailure(b,d,"no response",null)}else{h=true;a.transportSuccess(b,d,f)}}catch(j){a._debug(j);if(!h){c=false;a.transportFailure(b,d,"bad response",j)}}},onError:function(j,k){c=false;g?a.setTimeout(function(){a.transportFailure(b,d,j,k)},0):a.transportFailure(b,d,j,k)}});g=false}catch(j){c=false;this.setTimeout(function(){a.transportFailure(b,d,"error",j)},0)}};g.reset=function(){b.reset();
c=true};return g};
org.cometd.CallbackPollingTransport=function(){var b=new org.cometd.RequestTransport,b=org.cometd.Transport.derive(b);b.accept=function(){return true};b.jsonpSend=function(){throw"Abstract";};b.transportSend=function(b,c){for(var i=this,d=0,a=b.messages.length,h=[];a>0;){var j=org.cometd.JSON.toJSON(b.messages.slice(d,d+a)),j=b.url.length+encodeURI(j).length;if(j>2E3){if(a===1){var m="Bayeux message too big ("+j+" bytes, max is 2000) for transport "+this.getType();this.setTimeout(function(){i.transportFailure(b,c,
"error",m)},0);return}--a}else{h.push(a);d=d+a;a=b.messages.length-d}}var k=b;if(h.length>1){d=0;a=h[0];this._debug("Transport",this.getType(),"split",b.messages.length,"messages into",h.join(" + "));k=this._mixin(false,{},b);k.messages=b.messages.slice(d,a);k.onSuccess=b.onSuccess;k.onFailure=b.onFailure;for(j=1;j<h.length;++j){var f=this._mixin(false,{},b),d=a,a=a+h[j];f.messages=b.messages.slice(d,a);f.onSuccess=b.onSuccess;f.onFailure=b.onFailure;this.send(f,c.metaConnect)}}this._debug("Transport",
this.getType(),"sending request",c.id,"envelope",k);try{var o=true;this.jsonpSend({transport:this,url:k.url,sync:k.sync,headers:this.getConfiguration().requestHeaders,body:org.cometd.JSON.toJSON(k.messages),onSuccess:function(a){var b=false;try{var f=i.convertToMessages(a);if(f.length===0)i.transportFailure(k,c,"no response");else{b=true;i.transportSuccess(k,c,f)}}catch(d){i._debug(d);b||i.transportFailure(k,c,"bad response",d)}},onError:function(a,b){o?i.setTimeout(function(){i.transportFailure(k,
c,a,b)},0):i.transportFailure(k,c,a,b)}});o=false}catch(t){this.setTimeout(function(){i.transportFailure(k,c,"error",t)},0)}};return b};
org.cometd.WebSocketTransport=function(){function b(){var b=a.getURL().replace(/^http/,"ws");this._debug("Transport",this.getType(),"connecting to URL",b);var c=this,d=null,g=a.getConfiguration().connectTimeout;g>0&&(d=this.setTimeout(function(){d=null;if(!o){c._debug("Transport",c.getType(),"timed out while connecting to URL",b,":",g,"ms");c.onClose(1002,"Connect Timeout")}},g));var h=new org.cometd.WebSocket(b);h.onopen=function(){c._debug("WebSocket opened",h);if(d){c.clearTimeout(d);d=null}if(h!==
f)c._debug("Ignoring open event, WebSocket",f);else c.onOpen()};h.onclose=function(a){var b=a?a.code:1E3,a=a?a.reason:void 0;c._debug("WebSocket closed",b,"/",a,h);if(d){c.clearTimeout(d);d=null}if(h!==f)c._debug("Ignoring close event, WebSocket",f);else c.onClose(b,a)};h.onerror=function(){h.onclose({code:1002})};h.onmessage=function(a){c._debug("WebSocket message",a,h);if(h!==f)c._debug("Ignoring message event, WebSocket",f);else c.onMessage(a)};f=h;this._debug("Transport",this.getType(),"configured callbacks on",
h)}function g(a,c){var b=org.cometd.JSON.toJSON(a.messages);f.send(b);this._debug("Transport",this.getType(),"sent",a,"metaConnect =",c);var d=b=this.getConfiguration().maxNetworkDelay;if(c){d=d+this.getAdvice().timeout;t=true}for(var h=[],g=0;g<a.messages.length;++g){var i=a.messages[g];if(i.id){h.push(i.id);k[i.id]=this.setTimeout(function(){f&&f.close(1E3,"Timeout")},d)}}this._debug("Transport",this.getType(),"waiting at most",d,"ms for messages",h,"maxNetworkDelay",b,", timeouts:",k)}function c(a,
c){try{f===null?b.call(this):o&&g.call(this,a,c)}catch(d){this.setTimeout(function(){a.onFailure(f,a.messages,"error",d)},0)}}var i=new org.cometd.Transport,d=org.cometd.Transport.derive(i),a,h=true,j=false,m={},k={},f=null,o=false,t=false,u;d.onOpen=function(){this._debug("Transport",this.getType(),"opened",f);j=o=true;this._debug("Sending pending messages",m);for(var a in m){var c=m[a],b=c[0],c=c[1];u=b.onSuccess;g.call(this,b,c)}};d.onMessage=function(a){this._debug("Transport",this.getType(),
"received websocket message",a,f);for(var c=false,a=this.convertToMessages(a.data),b=[],d=0;d<a.length;++d){var h=a[d];if((/^\/meta\//.test(h.channel)||h.data===void 0)&&h.id){b.push(h.id);var g=k[h.id];if(g){this.clearTimeout(g);delete k[h.id];this._debug("Transport",this.getType(),"removed timeout for message",h.id,", timeouts",k)}}"/meta/connect"===h.channel&&(t=false);"/meta/disconnect"===h.channel&&!t&&(c=true)}d=false;for(h=0;h<b.length;++h){var i=b[h],j;for(j in m){var g=j.split(","),o=org.cometd.Utils.inArray(i,
g);if(o>=0){d=true;g.splice(o,1);i=m[j][0];o=m[j][1];delete m[j];g.length>0&&(m[g.join(",")]=[i,o]);break}}}d&&this._debug("Transport",this.getType(),"removed envelope, envelopes",m);u.call(this,a);c&&f.close(1E3,"Disconnect")};d.onClose=function(a,c){this._debug("Transport",this.getType(),"closed",a,c,f);h=j;for(var b in k)this.clearTimeout(k[b]);k={};for(var d in m){b=m[d][0];m[d][1]&&(t=false);b.onFailure(f,b.messages,"closed "+a+"/"+c)}m={};f!==null&&o&&f.close(1E3,"Close");o=false;f=null};d.registered=
function(c,b){i.registered(c,b);a=b};d.accept=function(){return h&&!!org.cometd.WebSocket&&a.websocketEnabled!==false};d.send=function(a,b){this._debug("Transport",this.getType(),"sending",a,"metaConnect =",b);for(var d=[],h=0;h<a.messages.length;++h){var f=a.messages[h];f.id&&d.push(f.id)}m[d.join(",")]=[a,b];this._debug("Transport",this.getType(),"stored envelope, envelopes",m);c.call(this,a,b)};d.reset=function(){i.reset();f!==null&&o&&f.close(1E3,"Reset");h=true;j=false;k={};m={};f=null;o=false;
u=null};return d};
org.cometd.Cometd=function(b){function g(e){return org.cometd.Utils.isString(e)}function c(e){return e===void 0||e===null?false:typeof e==="function"}function i(e,a){if(window.console){var b=window.console[e];c(b)&&b.apply(window.console,a)}}function d(){for(var e in w)for(var a=w[e],b=0;b<a.length;++b){var c=a[b];if(c&&!c.listener){delete a[b];l._debug("Removed subscription",c,"for channel",e)}}}function a(e){if(z!==e){l._debug("Status",z,"->",e);z=e}}function h(){return z==="disconnecting"||z===
"disconnected"}function j(e,a,b,d,h){try{return a.call(e,d)}catch(f){l._debug("Exception during execution of extension",b,f);e=l.onExtensionException;if(c(e)){l._debug("Invoking extension exception callback",b,f);try{e.call(l,f,b,h,d)}catch(g){l._info("Exception during execution of exception callback in extension",b,g)}}return d}}function m(e){for(var a=0;a<q.length;++a){if(e===void 0||e===null)break;var b=q[a],d=b.extension.outgoing;if(c(d)){b=j(b.extension,d,b.name,e,true);e=b===void 0?e:b}}return e}
function k(e,a){var b=w[e];if(b&&b.length>0)for(var d=0;d<b.length;++d){var f=b[d];if(f)try{f.callback.call(f.scope,a)}catch(h){l._debug("Exception during notification",f,a,h);var g=l.onListenerException;if(c(g)){l._debug("Invoking listener exception callback",f,h);try{g.call(l,h,f.handle,f.listener,a)}catch(i){l._info("Exception during execution of listener callback",f,i)}}}}}function f(e,a){k(e,a);for(var b=e.split("/"),c=b.length-1,d=c;d>0;--d){var f=b.slice(0,d).join("/")+"/*";d===c&&k(f,a);f=
f+"*";k(f,a)}}function o(){G!==null&&org.cometd.Utils.clearTimeout(G);G=null}function t(e){o();var a=r.interval+p;l._debug("Function scheduled in",a,"ms, interval =",r.interval,"backoff =",p,e);G=org.cometd.Utils.setTimeout(l,e,a)}function u(e,a,b,c){for(var d=0;d<a.length;++d){var f=a[d];f.id=""+ ++$;if(A)f.clientId=A;f=m(f);f!==void 0&&f!==null?a[d]=f:a.splice(d--,1)}if(a.length!==0){d=n.url;if(n.appendMessageTypeToURL){d.match(/\/$/)||(d=d+"/");c&&(d=d+c)}e={url:d,sync:e,messages:a,onSuccess:function(e){try{R.call(l,
e)}catch(a){l._debug("Exception during handling of messages",a)}},onFailure:function(e,a,b,c){try{J.call(l,e,a,b,c)}catch(d){l._debug("Exception during handling of failure",d)}}};l._debug("Send",e);v.send(e,b)}}function E(e){x>0||C===true?B.push(e):u(false,[e],false)}function F(){var e=B;B=[];e.length>0&&u(false,e,false)}function H(){a("connecting");t(function(){if(!h()){var e={channel:"/meta/connect",connectionType:v.getType()};if(!K)e.advice={timeout:0};a("connecting");l._debug("Connect sent",e);
u(false,[e],true,"connect");a("connected")}})}function I(e){if(e){r=l._mixin(false,{},n.advice,e);l._debug("New advice",r)}}function y(e){o();e&&v.abort();A=null;a("disconnected");p=x=0;if(B.length>0){J.call(l,void 0,B,"error","Disconnected");B=[]}}function N(e){A=null;d();if(h()){s.reset();I(n.advice)}else I(l._mixin(false,r,{reconnect:"retry"}));x=0;C=true;L=e;var e=s.findTransportTypes("1.0",D,n.url),b=l._mixin(false,{},L,{version:"1.0",minimumVersion:"0.9",channel:"/meta/handshake",supportedConnectionTypes:e,
advice:{timeout:r.timeout,interval:r.interval}});v=s.negotiateTransport(e,"1.0",D,n.url);l._debug("Initial transport is",v.getType());a("handshaking");l._debug("Handshake sent",b);u(false,[b],false,"handshake")}function O(){a("handshaking");C=true;t(function(){N(L)})}function P(e){f("/meta/handshake",e);f("/meta/unsuccessful",e);if(!h()&&r.reconnect!=="none"){p<n.maxBackoff&&(p=p+n.backoffIncrement);O()}else y(false)}function Q(e){f("/meta/connect",e);f("/meta/unsuccessful",e);e=h()?"none":r.reconnect;
switch(e){case "retry":H();p<n.maxBackoff&&(p=p+n.backoffIncrement);break;case "handshake":s.reset();p=0;O();break;case "none":y(false);break;default:throw"Unrecognized advice action"+e;}}function S(e){y(true);f("/meta/disconnect",e);f("/meta/unsuccessful",e)}function T(e){f("/meta/subscribe",e);f("/meta/unsuccessful",e)}function U(e){f("/meta/unsubscribe",e);f("/meta/unsuccessful",e)}function V(e){f("/meta/publish",e);f("/meta/unsuccessful",e)}function W(e){for(var a=0;a<q.length;++a){if(e===void 0||
e===null)break;var b=q[n.reverseIncomingExtensions?q.length-1-a:a],d=b.extension.incoming;if(c(d)){b=j(b.extension,d,b.name,e,false);e=b===void 0?e:b}}if(!(e===void 0||e===null)){I(e.advice);switch(e.channel){case "/meta/handshake":if(e.successful){A=e.clientId;a=s.negotiateTransport(e.supportedConnectionTypes,e.version,D,n.url);if(a===null)throw"Could not negotiate transport with server; client "+s.findTransportTypes(e.version,D,n.url)+", server "+e.supportedConnectionTypes;if(v!==a){l._debug("Transport",
v,"->",a);v=a}C=false;F();e.reestablish=M;M=true;f("/meta/handshake",e);e=h()?"none":r.reconnect;switch(e){case "retry":p=0;H();break;case "none":y(false);break;default:throw"Unrecognized advice action "+e;}}else P(e);break;case "/meta/connect":if(K=e.successful){f("/meta/connect",e);e=h()?"none":r.reconnect;switch(e){case "retry":p=0;H();break;case "none":y(false);break;default:throw"Unrecognized advice action "+e;}}else Q(e);break;case "/meta/disconnect":if(e.successful){y(false);f("/meta/disconnect",
e)}else S(e);break;case "/meta/subscribe":e.successful?f("/meta/subscribe",e):T(e);break;case "/meta/unsubscribe":e.successful?f("/meta/unsubscribe",e):U(e);break;default:e.successful===void 0?e.data?f(e.channel,e):l._debug("Unknown message",e):e.successful?f("/meta/publish",e):V(e)}}}function X(e){if(e=w[e])for(var a=0;a<e.length;++a)if(e[a])return true;return false}function Y(e,a){var b={scope:e,method:a};if(c(e)){b.scope=void 0;b.method=e}else if(g(a)){if(!e)throw"Invalid scope "+e;b.method=e[a];
if(!c(b.method))throw"Invalid callback "+a+" for scope "+e;}else if(!c(a))throw"Invalid callback "+a;return b}function Z(e,a,b,c){a=Y(a,b);l._debug("Adding listener on",e,"with scope",a.scope,"and callback",a.method);c={channel:e,scope:a.scope,callback:a.method,listener:c};a=w[e];if(!a){a=[];w[e]=a}a=a.push(c)-1;c.id=a;c.handle=[e,a];l._debug("Added listener",c,"for channel",e,"having id =",a);return c.handle}var l=this,aa=b||"default",D=false,s=new org.cometd.TransportRegistry,v,z="disconnected",
$=0,A=null,x=0,B=[],C=false,w={},p=0,G=null,q=[],r={},L,M=false,K=false,n={connectTimeout:0,maxConnections:2,backoffIncrement:1E3,maxBackoff:6E4,logLevel:"info",reverseIncomingExtensions:true,maxNetworkDelay:1E4,requestHeaders:{},appendMessageTypeToURL:true,autoBatch:false,advice:{timeout:6E4,interval:0,reconnect:"retry"}};this._mixin=function(a,b,c){for(var d=b||{},f=2;f<arguments.length;++f){var h=arguments[f];if(!(h===void 0||h===null))for(var g in h){var i=h[g],j=d[g];i!==b&&i!==void 0&&(d[g]=
a&&typeof i==="object"&&i!==null?i instanceof Array?this._mixin(a,j instanceof Array?j:[],i):this._mixin(a,typeof j==="object"&&!(j instanceof Array)?j:{},i):i)}}return d};this._warn=function(){i("warn",arguments)};this._info=function(){n.logLevel!=="warn"&&i("info",arguments)};this._debug=function(){n.logLevel==="debug"&&i("debug",arguments)};this._isCrossDomain=function(a){return a&&a!==window.location.host};var R,J;this.send=E;this.receive=W;R=function(a){l._debug("Received",a);for(var b=0;b<a.length;++b)W(a[b])};
J=function(a,b,c,d){l._debug("handleFailure",a,b,c,d);for(c=0;c<b.length;++c){var f=b[c];switch(f.channel){case "/meta/handshake":P({successful:false,failure:true,channel:"/meta/handshake",request:f,xhr:a,advice:{reconnect:"retry",interval:p}});break;case "/meta/connect":d=a;K=false;Q({successful:false,failure:true,channel:"/meta/connect",request:f,xhr:d,advice:{reconnect:"retry",interval:p}});break;case "/meta/disconnect":S({successful:false,failure:true,channel:"/meta/disconnect",request:f,xhr:a,
advice:{reconnect:"none",interval:0}});break;case "/meta/subscribe":T({successful:false,failure:true,channel:"/meta/subscribe",request:f,xhr:a,advice:{reconnect:"none",interval:0}});break;case "/meta/unsubscribe":U({successful:false,failure:true,channel:"/meta/unsubscribe",request:f,xhr:a,advice:{reconnect:"none",interval:0}});break;default:V({successful:false,failure:true,channel:f.channel,request:f,xhr:a,advice:{reconnect:"none",interval:0}})}}};this.registerTransport=function(a,b,d){if(d=s.add(a,
b,d)){this._debug("Registered transport",a);c(b.registered)&&b.registered(a,this)}return d};this.getTransportTypes=function(){return s.getTransportTypes()};this.unregisterTransport=function(a){var b=s.remove(a);if(b!==null){this._debug("Unregistered transport",a);c(b.unregistered)&&b.unregistered()}return b};this.unregisterTransports=function(){s.clear()};this.findTransport=function(a){return s.find(a)};this.configure=function(a){l._debug("Configuring cometd object with",a);g(a)&&(a={url:a});a||(a=
{});n=l._mixin(false,n,a);if(!n.url)throw"Missing required configuration parameter 'url' specifying the Bayeux server URL";var b=/(^https?:\/\/)?(((\[[^\]]+\])|([^:\/\?#]+))(:(\d+))?)?([^\?#]*)(.*)?/.exec(n.url),a=b[8],c=b[9];D=l._isCrossDomain(b[2]);if(n.appendMessageTypeToURL)if(c!==void 0&&c.length>0){l._info("Appending message type to URI "+a+c+" is not supported, disabling 'appendMessageTypeToURL' configuration");n.appendMessageTypeToURL=false}else{b=a.split("/");c=b.length-1;a.match(/\/$/)&&
(c=c-1);if(b[c].indexOf(".")>=0){l._info("Appending message type to URI "+a+" is not supported, disabling 'appendMessageTypeToURL' configuration");n.appendMessageTypeToURL=false}}};this.init=function(a,b){this.configure(a);this.handshake(b)};this.handshake=function(b){a("disconnected");M=false;N(b)};this.disconnect=function(b,c){if(!h()){if(c===void 0&&typeof b!=="boolean"){c=b;b=false}var d=this._mixin(false,{},c,{channel:"/meta/disconnect"});a("disconnecting");u(b===true,[d],false,"disconnect")}};
this.startBatch=function(){++x};this.endBatch=function(){--x;if(x<0)throw"Calls to startBatch() and endBatch() are not paired";x===0&&!h()&&!C&&F()};this.batch=function(a,b){var c=Y(a,b);this.startBatch();try{c.method.call(c.scope);this.endBatch()}catch(d){this._debug("Exception during execution of batch",d);this.endBatch();throw d;}};this.addListener=function(a,b,c){if(arguments.length<2)throw"Illegal arguments number: required 2, got "+arguments.length;if(!g(a))throw"Illegal argument type: channel must be a string";
return Z(a,b,c,true)};this.removeListener=function(a){if(!org.cometd.Utils.isArray(a))throw"Invalid argument: expected subscription, not "+a;var b=w[a[0]];if(b){delete b[a[1]];l._debug("Removed listener",a)}};this.clearListeners=function(){w={}};this.subscribe=function(a,b,d,f){if(arguments.length<2)throw"Illegal arguments number: required 2, got "+arguments.length;if(!g(a))throw"Illegal argument type: channel must be a string";if(h())throw"Illegal state: already disconnected";if(c(b)){f=d;d=b;b=
void 0}var i=!X(a),j=Z(a,b,d,false);if(i){i=this._mixin(false,{},f,{channel:"/meta/subscribe",subscription:a});E(i)}return j};this.unsubscribe=function(a,b){if(arguments.length<1)throw"Illegal arguments number: required 1, got "+arguments.length;if(h())throw"Illegal state: already disconnected";this.removeListener(a);var c=a[0];if(!X(c)){c=this._mixin(false,{},b,{channel:"/meta/unsubscribe",subscription:c});E(c)}};this.clearSubscriptions=function(){d()};this.publish=function(a,b,c){if(arguments.length<
1)throw"Illegal arguments number: required 1, got "+arguments.length;if(!g(a))throw"Illegal argument type: channel must be a string";if(h())throw"Illegal state: already disconnected";var d=this._mixin(false,{},c,{channel:a,data:b});E(d)};this.getStatus=function(){return z};this.isDisconnected=h;this.setBackoffIncrement=function(a){n.backoffIncrement=a};this.getBackoffIncrement=function(){return n.backoffIncrement};this.getBackoffPeriod=function(){return p};this.setLogLevel=function(a){n.logLevel=
a};this.registerExtension=function(a,b){if(arguments.length<2)throw"Illegal arguments number: required 2, got "+arguments.length;if(!g(a))throw"Illegal argument type: extension name must be a string";for(var d=false,f=0;f<q.length;++f)if(q[f].name===a){d=true;break}if(d){this._info("Could not register extension with name",a,"since another extension with the same name already exists");return false}q.push({name:a,extension:b});this._debug("Registered extension",a);c(b.registered)&&b.registered(a,this);
return true};this.unregisterExtension=function(a){if(!g(a))throw"Illegal argument type: extension name must be a string";for(var b=false,d=0;d<q.length;++d){var f=q[d];if(f.name===a){q.splice(d,1);b=true;this._debug("Unregistered extension",a);a=f.extension;c(a.unregistered)&&a.unregistered();break}}return b};this.getExtension=function(a){for(var b=0;b<q.length;++b){var c=q[b];if(c.name===a)return c.extension}return null};this.getName=function(){return aa};this.getClientId=function(){return A};this.getURL=
function(){return n.url};this.getTransport=function(){return v};this.getConfiguration=function(){return this._mixin(true,{},n)};this.getAdvice=function(){return this._mixin(true,{},r)};org.cometd.WebSocket=window.WebSocket;if(!org.cometd.WebSocket)org.cometd.WebSocket=window.MozWebSocket};"undefined"!=typeof dojo&&dojo.provide("org.cometd.ReloadExtension");org.cometd.COOKIE||(org.cometd.COOKIE={},org.cometd.COOKIE.set=function(){throw"Abstract";},org.cometd.COOKIE.get=function(){throw"Abstract";});
org.cometd.ReloadExtension=function(b){function g(b){if(a&&a.handshakeResponse!==null){c(b);a.cookiePath=j;b=org.cometd.JSON.toJSON(a);d("Reload extension saving cookie value",b);org.cometd.COOKIE.set(h,b,{"max-age":m,path:j,expires:new Date((new Date).getTime()+m*1E3)})}}function c(a){if(a){if(typeof a.cookieMaxAge==="number")m=a.cookieMaxAge;if(typeof a.cookieName==="string")h=a.cookieName;if(typeof a.cookiePath==="string")j=a.cookiePath}}var i,d,a=null,h="org.cometd.reload",j="/",m=5,k=false;this.configure=
c;this.registered=function(a,b){i=b;i.reload=g;d=i._debug};this.unregistered=function(){delete i.reload;i=null};this.outgoing=function(b){var c=b.channel;if(c=="/meta/handshake"){a={};a.url=i.getURL();c=org.cometd.COOKIE.get(h);d("Reload extension found cookie value",c);if(c)try{var g=org.cometd.JSON.fromJSON(c);org.cometd.COOKIE.set(h,"",{"max-age":-1,path:g.cookiePath,expires:-1});if(g.handshakeResponse&&a.url==g.url){d("Reload extension restoring state",g);setTimeout(function(){d("Reload extension replaying handshake response",
g.handshakeResponse);a.handshakeResponse=g.handshakeResponse;a.transportType=g.transportType;a.reloading=true;var b=i._mixin(true,{},a.handshakeResponse,{ext:{reload:true}});b.supportedConnectionTypes=[a.transportType];i.receive(b);d("Reload extension replayed handshake response",b)},0);if(!k){k=true;i.startBatch()}return null}d("Reload extension could not restore state",g)}catch(j){d("Reload extension error while trying to restore cookie",j)}}else if(c=="/meta/connect"&&!a.transportType){a.transportType=
b.connectionType;d("Reload extension tracked transport type",a.transportType)}return b};this.incoming=function(b){if(b.successful)switch(b.channel){case "/meta/handshake":if(!a.handshakeResponse){a.handshakeResponse=b;d("Reload extension tracked handshake response",b)}break;case "/meta/disconnect":a=null;break;case "/meta/connect":if(k){i.endBatch();k=false}}return b};c(b)};
(function(b){function g(b,a){if(a)for(var c in a)c.toLowerCase()!=="content-type"&&b.setRequestHeader(c,a[c])}function c(){var c=new org.cometd.LongPollingTransport,c=org.cometd.Transport.derive(c);c.xhrSend=function(a){return b.ajax({url:a.url,async:a.sync!==true,type:"POST",contentType:"application/json;charset=UTF-8",data:a.body,xhrFields:{withCredentials:true},beforeSend:function(b){g(b,a.headers);return true},success:a.onSuccess,error:function(b,c,d){a.onError(c,d)}})};return c}function i(){var c=
new org.cometd.CallbackPollingTransport,c=org.cometd.Transport.derive(c);c.jsonpSend=function(a){b.ajax({url:a.url,async:a.sync!==true,type:"GET",dataType:"jsonp",jsonp:"jsonp",data:{message:a.body},beforeSend:function(b){g(b,a.headers);return true},success:a.onSuccess,error:function(b,c,d){a.onError(c,d)}})};return c}org.cometd.JSON.toJSON=JSON.stringify;org.cometd.JSON.fromJSON=JSON.parse;b.Cometd=function(b){b=new org.cometd.Cometd(b);org.cometd.WebSocket&&b.registerTransport("websocket",new org.cometd.WebSocketTransport);
b.registerTransport("long-polling",new c);b.registerTransport("callback-polling",new i);return b};b.cometd=new b.Cometd})(jQuery);(function(b){if(b.cookie){org.cometd.COOKIE.set=b.cookie;org.cometd.COOKIE.get=b.cookie}b.cometd.registerExtension("reload",new org.cometd.ReloadExtension)})(jQuery);
