/*
Copyright 2012, KISS UI Library v0.7.1
MIT Licensed
build time: Sep 4 15:37
*/(function(o,n){function t(a){var b=ya[a]={};return c.each(a.split(A),function(a,c){b[c]=!0}),b}function z(a,b,d){if(d===n&&1===a.nodeType)if(d="data-"+b.replace(yb,"-$1").toLowerCase(),d=a.getAttribute(d),"string"==typeof d){try{d="true"===d?!0:"false"===d?!1:"null"===d?null:+d+""===d?+d:zb.test(d)?c.parseJSON(d):d}catch(e){}c.data(a,b,d)}else d=n;return d}function I(a){for(var b in a)if(!("data"===b&&c.isEmptyObject(a[b]))&&"toJSON"!==b)return!1;return!0}function u(){return!1}function Y(){return!0}
function P(a){return!a||!a.parentNode||11===a.parentNode.nodeType}function za(a,b){do a=a[b];while(a&&1!==a.nodeType);return a}function Aa(a,b,d){b=b||0;if(c.isFunction(b))return c.grep(a,function(a,c){return!!b.call(a,c,a)===d});if(b.nodeType)return c.grep(a,function(a){return a===b===d});if("string"==typeof b){var e=c.grep(a,function(a){return 1===a.nodeType});if(Ab.test(b))return c.filter(b,e,!d);b=c.filter(b,e)}return c.grep(a,function(a){return 0<=c.inArray(a,b)===d})}function Ba(a){var b=Ca.split("|"),
a=a.createDocumentFragment();if(a.createElement)for(;b.length;)a.createElement(b.pop());return a}function Da(a,b){if(1===b.nodeType&&c.hasData(a)){var d,e,f;e=c._data(a);var g=c._data(b,e),h=e.events;if(h)for(d in delete g.handle,g.events={},h){e=0;for(f=h[d].length;e<f;e++)c.event.add(b,d,h[d][e])}g.data&&(g.data=c.extend({},g.data))}}function Ea(a,b){var d;1===b.nodeType&&(b.clearAttributes&&b.clearAttributes(),b.mergeAttributes&&b.mergeAttributes(a),d=b.nodeName.toLowerCase(),"object"===d?(b.parentNode&&
(b.outerHTML=a.outerHTML),c.support.html5Clone&&a.innerHTML&&!c.trim(b.innerHTML)&&(b.innerHTML=a.innerHTML)):"input"===d&&Fa.test(a.type)?(b.defaultChecked=b.checked=a.checked,b.value!==a.value&&(b.value=a.value)):"option"===d?b.selected=a.defaultSelected:"input"===d||"textarea"===d?b.defaultValue=a.defaultValue:"script"===d&&b.text!==a.text&&(b.text=a.text),b.removeAttribute(c.expando))}function $(a){return"undefined"!=typeof a.getElementsByTagName?a.getElementsByTagName("*"):"undefined"!=typeof a.querySelectorAll?
a.querySelectorAll("*"):[]}function Ga(a){Fa.test(a.type)&&(a.defaultChecked=a.checked)}function Ha(a,b){if(b in a)return b;for(var d=b.charAt(0).toUpperCase()+b.slice(1),c=b,f=Ia.length;f--;)if(b=Ia[f]+d,b in a)return b;return c}function aa(a,b){return a=b||a,"none"===c.css(a,"display")||!c.contains(a.ownerDocument,a)}function Ja(a,b){for(var d,e,f=[],g=0,h=a.length;g<h;g++)d=a[g],d.style&&(f[g]=c._data(d,"olddisplay"),b?(!f[g]&&"none"===d.style.display&&(d.style.display=""),""===d.style.display&&
aa(d)&&(f[g]=c._data(d,"olddisplay",Ka(d.nodeName)))):(e=r(d,"display"),!f[g]&&"none"!==e&&c._data(d,"olddisplay",e)));for(g=0;g<h;g++)if(d=a[g],d.style&&(!b||"none"===d.style.display||""===d.style.display))d.style.display=b?f[g]||"":"none";return a}function La(a,b,d){return(a=Bb.exec(b))?Math.max(0,a[1]-(d||0))+(a[2]||"px"):b}function Ma(a,b,d,e){for(var b=d===(e?"border":"content")?4:"width"===b?1:0,f=0;4>b;b+=2)"margin"===d&&(f+=c.css(a,d+N[b],!0)),e?("content"===d&&(f-=parseFloat(r(a,"padding"+
N[b]))||0),"margin"!==d&&(f-=parseFloat(r(a,"border"+N[b]+"Width"))||0)):(f+=parseFloat(r(a,"padding"+N[b]))||0,"padding"!==d&&(f+=parseFloat(r(a,"border"+N[b]+"Width"))||0));return f}function Na(a,b,d){var e="width"===b?a.offsetWidth:a.offsetHeight,f=!0,g=c.support.boxSizing&&"border-box"===c.css(a,"boxSizing");if(0>=e||null==e){e=r(a,b);if(0>e||null==e)e=a.style[b];if(ba.test(e))return e;f=g&&(c.support.boxSizingReliable||e===a.style[b]);e=parseFloat(e)||0}return e+Ma(a,b,d||(g?"border":"content"),
f)+"px"}function Ka(a){if(ma[a])return ma[a];var b=c("<"+a+">").appendTo(m.body),d=b.css("display");b.remove();if("none"===d||""===d){Q=m.body.appendChild(Q||c.extend(m.createElement("iframe"),{frameBorder:0,width:0,height:0}));if(!R||!Q.createElement)R=(Q.contentWindow||Q.contentDocument).document,R.write("<!doctype html><html><body>"),R.close();b=R.body.appendChild(R.createElement(a));d=r(b,"display");m.body.removeChild(Q)}return ma[a]=d,d}function na(a,b,d,e){var f;if(c.isArray(b))c.each(b,function(b,
c){d||Cb.test(a)?e(a,c):na(a+"["+("object"==typeof c?b:"")+"]",c,d,e)});else if(!d&&"object"===c.type(b))for(f in b)na(a+"["+f+"]",b[f],d,e);else e(a,b)}function Oa(a){return function(b,d){"string"!=typeof b&&(d=b,b="*");var e,f,g=b.toLowerCase().split(A),h=0,i=g.length;if(c.isFunction(d))for(;h<i;h++)e=g[h],(f=/^\+/.test(e))&&(e=e.substr(1)||"*"),e=a[e]=a[e]||[],e[f?"unshift":"push"](d)}}function ca(a,b,d,c,f,g){f=f||b.dataTypes[0];g=g||{};g[f]=!0;for(var h,f=a[f],i=0,j=f?f.length:0,k=a===oa;i<j&&
(k||!h);i++)h=f[i](b,d,c),"string"==typeof h&&(!k||g[h]?h=n:(b.dataTypes.unshift(h),h=ca(a,b,d,c,h,g)));return(k||!h)&&!g["*"]&&(h=ca(a,b,d,c,"*",g)),h}function Pa(a,b){var d,e,f=c.ajaxSettings.flatOptions||{};for(d in b)b[d]!==n&&((f[d]?a:e||(e={}))[d]=b[d]);e&&c.extend(!0,a,e)}function Qa(){try{return new o.XMLHttpRequest}catch(a){}}function Ra(){return setTimeout(function(){da=n},0),da=c.now()}function Db(a,b){c.each(b,function(b,c){for(var f=(V[b]||[]).concat(V["*"]),g=0,h=f.length;g<h&&!f[g].call(a,
b,c);g++);})}function Sa(a,b,d){var e=0,f=ea.length,g=c.Deferred().always(function(){delete h.elem}),h=function(){for(var b=da||Ra(),b=Math.max(0,i.startTime+i.duration-b),d=1-(b/i.duration||0),c=0,e=i.tweens.length;c<e;c++)i.tweens[c].run(d);return g.notifyWith(a,[i,d,b]),1>d&&e?b:(g.resolveWith(a,[i]),!1)},i=g.promise({elem:a,props:c.extend({},b),opts:c.extend(!0,{specialEasing:{}},d),originalProperties:b,originalOptions:d,startTime:da||Ra(),duration:d.duration,tweens:[],createTween:function(b,
d){var e=c.Tween(a,i.opts,b,d,i.opts.specialEasing[b]||i.opts.easing);return i.tweens.push(e),e},stop:function(b){for(var d=0,c=b?i.tweens.length:0;d<c;d++)i.tweens[d].run(1);return b?g.resolveWith(a,[i,b]):g.rejectWith(a,[i,b]),this}}),d=i.props;for(Eb(d,i.opts.specialEasing);e<f;e++)if(b=ea[e].call(i,a,d,i.opts))return b;return Db(i,d),c.isFunction(i.opts.start)&&i.opts.start.call(a,i),c.fx.timer(c.extend(h,{anim:i,queue:i.opts.queue,elem:a})),i.progress(i.opts.progress).done(i.opts.done,i.opts.complete).fail(i.opts.fail).always(i.opts.always)}
function Eb(a,b){var d,e,f,g,h;for(d in a)if(e=c.camelCase(d),f=b[e],g=a[d],c.isArray(g)&&(f=g[1],g=a[d]=g[0]),d!==e&&(a[e]=g,delete a[d]),(h=c.cssHooks[e])&&"expand"in h)for(d in g=h.expand(g),delete a[e],g)d in a||(a[d]=g[d],b[d]=f);else b[e]=f}function B(a,b,d,c,f){return new B.prototype.init(a,b,d,c,f)}function fa(a,b){for(var d,c={height:a},f=0,b=b?1:0;4>f;f+=2-b)d=N[f],c["margin"+d]=c["padding"+d]=a;return b&&(c.opacity=c.width=a),c}function Ta(a){return c.isWindow(a)?a:9===a.nodeType?a.defaultView||
a.parentWindow:!1}var Ua,ga,m=o.document,Fb=o.location,Gb=o.navigator,Hb=o.jQuery,Ib=o.$,Va=Array.prototype.push,C=Array.prototype.slice,Wa=Array.prototype.indexOf,Jb=Object.prototype.toString,pa=Object.prototype.hasOwnProperty,qa=String.prototype.trim,c=function(a,b){return new c.fn.init(a,b,Ua)},ha=/[\-+]?(?:\d*\.|)\d+(?:[eE][\-+]?\d+|)/.source,Kb=/\S/,A=/\s+/,Lb=/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g,Mb=/^(?:[^#<]*(<[\w\W]+>)[^>]*$|#([\w\-]*)$)/,Xa=/^<(\w+)\s*\/?>(?:<\/\1>|)$/,Nb=/^[\],:{}\s]*$/,
Ob=/(?:^|:|,)(?:\s*\[)+/g,Pb=/\\(?:["\\\/bfnrt]|u[\da-fA-F]{4})/g,Qb=/"[^"\\\r\n]*"|true|false|null|-?(?:\d\d*\.|)\d+(?:[eE][\-+]?\d+|)/g,Rb=/^-ms-/,Sb=/-([\da-z])/gi,Tb=function(a,b){return(b+"").toUpperCase()},ia=function(){m.addEventListener?(m.removeEventListener("DOMContentLoaded",ia,!1),c.ready()):"complete"===m.readyState&&(m.detachEvent("onreadystatechange",ia),c.ready())},Ya={};c.fn=c.prototype={constructor:c,init:function(a,b,d){var e,f;if(!a)return this;if(a.nodeType)return this.context=
this[0]=a,this.length=1,this;if("string"==typeof a){"<"===a.charAt(0)&&">"===a.charAt(a.length-1)&&3<=a.length?e=[null,a,null]:e=Mb.exec(a);if(e&&(e[1]||!b)){if(e[1])return b=b instanceof c?b[0]:b,f=b&&b.nodeType?b.ownerDocument||b:m,a=c.parseHTML(e[1],f,!0),Xa.test(e[1])&&c.isPlainObject(b)&&this.attr.call(a,b,!0),c.merge(this,a);if((b=m.getElementById(e[2]))&&b.parentNode){if(b.id!==e[2])return d.find(a);this.length=1;this[0]=b}return this.context=m,this.selector=a,this}return!b||b.jquery?(b||d).find(a):
this.constructor(b).find(a)}return c.isFunction(a)?d.ready(a):(a.selector!==n&&(this.selector=a.selector,this.context=a.context),c.makeArray(a,this))},selector:"",jquery:"1.8.1",length:0,size:function(){return this.length},toArray:function(){return C.call(this)},get:function(a){return null==a?this.toArray():0>a?this[this.length+a]:this[a]},pushStack:function(a,b,d){a=c.merge(this.constructor(),a);return a.prevObject=this,a.context=this.context,"find"===b?a.selector=this.selector+(this.selector?" ":
"")+d:b&&(a.selector=this.selector+"."+b+"("+d+")"),a},each:function(a,b){return c.each(this,a,b)},ready:function(a){return c.ready.promise().done(a),this},eq:function(a){return a=+a,-1===a?this.slice(a):this.slice(a,a+1)},first:function(){return this.eq(0)},last:function(){return this.eq(-1)},slice:function(){return this.pushStack(C.apply(this,arguments),"slice",C.call(arguments).join(","))},map:function(a){return this.pushStack(c.map(this,function(b,d){return a.call(b,d,b)}))},end:function(){return this.prevObject||
this.constructor(null)},push:Va,sort:[].sort,splice:[].splice};c.fn.init.prototype=c.fn;c.extend=c.fn.extend=function(){var a,b,d,e,f,g,h=arguments[0]||{},i=1,j=arguments.length,k=!1;"boolean"==typeof h&&(k=h,h=arguments[1]||{},i=2);"object"!=typeof h&&!c.isFunction(h)&&(h={});for(j===i&&(h=this,--i);i<j;i++)if(null!=(a=arguments[i]))for(b in a)d=h[b],e=a[b],h!==e&&(k&&e&&(c.isPlainObject(e)||(f=c.isArray(e)))?(f?(f=!1,g=d&&c.isArray(d)?d:[]):g=d&&c.isPlainObject(d)?d:{},h[b]=c.extend(k,g,e)):e!==
n&&(h[b]=e));return h};c.extend({noConflict:function(a){return o.$===c&&(o.$=Ib),a&&o.jQuery===c&&(o.jQuery=Hb),c},isReady:!1,readyWait:1,holdReady:function(a){a?c.readyWait++:c.ready(!0)},ready:function(a){if(!(!0===a?--c.readyWait:c.isReady)){if(!m.body)return setTimeout(c.ready,1);c.isReady=!0;!0!==a&&0<--c.readyWait||(ga.resolveWith(m,[c]),c.fn.trigger&&c(m).trigger("ready").off("ready"))}},isFunction:function(a){return"function"===c.type(a)},isArray:Array.isArray||function(a){return"array"===
c.type(a)},isWindow:function(a){return null!=a&&a==a.window},isNumeric:function(a){return!isNaN(parseFloat(a))&&isFinite(a)},type:function(a){return null==a?""+a:Ya[Jb.call(a)]||"object"},isPlainObject:function(a){if(!a||"object"!==c.type(a)||a.nodeType||c.isWindow(a))return!1;try{if(a.constructor&&!pa.call(a,"constructor")&&!pa.call(a.constructor.prototype,"isPrototypeOf"))return!1}catch(b){return!1}for(var d in a);return d===n||pa.call(a,d)},isEmptyObject:function(a){for(var b in a)return!1;return!0},
error:function(a){throw Error(a);},parseHTML:function(a,b,d){var e;return!a||"string"!=typeof a?null:("boolean"==typeof b&&(d=b,b=0),b=b||m,(e=Xa.exec(a))?[b.createElement(e[1])]:(e=c.buildFragment([a],b,d?null:[]),c.merge([],(e.cacheable?c.clone(e.fragment):e.fragment).childNodes)))},parseJSON:function(a){if(!a||"string"!=typeof a)return null;a=c.trim(a);if(o.JSON&&o.JSON.parse)return o.JSON.parse(a);if(Nb.test(a.replace(Pb,"@").replace(Qb,"]").replace(Ob,"")))return(new Function("return "+a))();
c.error("Invalid JSON: "+a)},parseXML:function(a){var b,d;if(!a||"string"!=typeof a)return null;try{o.DOMParser?(d=new DOMParser,b=d.parseFromString(a,"text/xml")):(b=new ActiveXObject("Microsoft.XMLDOM"),b.async="false",b.loadXML(a))}catch(e){b=n}return(!b||!b.documentElement||b.getElementsByTagName("parsererror").length)&&c.error("Invalid XML: "+a),b},noop:function(){},globalEval:function(a){a&&Kb.test(a)&&(o.execScript||function(a){o.eval.call(o,a)})(a)},camelCase:function(a){return a.replace(Rb,
"ms-").replace(Sb,Tb)},nodeName:function(a,b){return a.nodeName&&a.nodeName.toUpperCase()===b.toUpperCase()},each:function(a,b,d){var e,f=0,g=a.length,h=g===n||c.isFunction(a);if(d)if(h)for(e in a){if(!1===b.apply(a[e],d))break}else for(;f<g&&!1!==b.apply(a[f++],d););else if(h)for(e in a){if(!1===b.call(a[e],e,a[e]))break}else for(;f<g&&!1!==b.call(a[f],f,a[f++]););return a},trim:qa&&!qa.call("\u00a0")?function(a){return null==a?"":qa.call(a)}:function(a){return null==a?"":a.toString().replace(Lb,"")},
makeArray:function(a,b){var d,e=b||[];return null!=a&&(d=c.type(a),null==a.length||"string"===d||"function"===d||"regexp"===d||c.isWindow(a)?Va.call(e,a):c.merge(e,a)),e},inArray:function(a,b,d){var c;if(b){if(Wa)return Wa.call(b,a,d);c=b.length;for(d=d?0>d?Math.max(0,c+d):d:0;d<c;d++)if(d in b&&b[d]===a)return d}return-1},merge:function(a,b){var d=b.length,c=a.length,f=0;if("number"==typeof d)for(;f<d;f++)a[c++]=b[f];else for(;b[f]!==n;)a[c++]=b[f++];return a.length=c,a},grep:function(a,b,c){for(var e,
f=[],g=0,h=a.length,c=!!c;g<h;g++)e=!!b(a[g],g),c!==e&&f.push(a[g]);return f},map:function(a,b,d){var e,f,g=[],h=0,i=a.length;if(a instanceof c||i!==n&&"number"==typeof i&&(0<i&&a[0]&&a[i-1]||0===i||c.isArray(a)))for(;h<i;h++)e=b(a[h],h,d),null!=e&&(g[g.length]=e);else for(f in a)e=b(a[f],f,d),null!=e&&(g[g.length]=e);return g.concat.apply([],g)},guid:1,proxy:function(a,b){var d,e,f;return"string"==typeof b&&(d=a[b],b=a,a=d),c.isFunction(a)?(e=C.call(arguments,2),f=function(){return a.apply(b,e.concat(C.call(arguments)))},
f.guid=a.guid=a.guid||f.guid||c.guid++,f):n},access:function(a,b,d,e,f,g,h){var i,j=null==d,k=0,p=a.length;if(d&&"object"==typeof d){for(k in d)c.access(a,b,k,d[k],1,g,e);f=1}else if(e!==n){i=h===n&&c.isFunction(e);j&&(i?(i=b,b=function(a,b,d){return i.call(c(a),d)}):(b.call(a,e),b=null));if(b)for(;k<p;k++)b(a[k],d,i?e.call(a[k],k,b(a[k],d)):e,h);f=1}return f?a:j?b.call(a):p?b(a[0],d):g},now:function(){return(new Date).getTime()}});c.ready.promise=function(a){if(!ga)if(ga=c.Deferred(),"complete"===
m.readyState)setTimeout(c.ready,1);else if(m.addEventListener)m.addEventListener("DOMContentLoaded",ia,!1),o.addEventListener("load",c.ready,!1);else{m.attachEvent("onreadystatechange",ia);o.attachEvent("onload",c.ready);var b=!1;try{b=null==o.frameElement&&m.documentElement}catch(d){}b&&b.doScroll&&function f(){if(!c.isReady){try{b.doScroll("left")}catch(a){return setTimeout(f,50)}c.ready()}}()}return ga.promise(a)};c.each("Boolean,Number,String,Function,Array,Date,RegExp,Object".split(","),function(a,
b){Ya["[object "+b+"]"]=b.toLowerCase()});Ua=c(m);var ya={};c.Callbacks=function(a){var a="string"==typeof a?ya[a]||t(a):c.extend({},a),b,d,e,f,g,h,i=[],j=!a.once&&[],k=function(c){b=a.memory&&c;d=!0;h=f||0;f=0;g=i.length;for(e=!0;i&&h<g;h++)if(!1===i[h].apply(c[0],c[1])&&a.stopOnFalse){b=!1;break}e=!1;i&&(j?j.length&&k(j.shift()):b?i=[]:p.disable())},p={add:function(){if(i){var d=i.length;(function v(b){c.each(b,function(b,d){var e=c.type(d);"function"===e&&(!a.unique||!p.has(d))?i.push(d):d&&d.length&&
"string"!==e&&v(d)})})(arguments);e?g=i.length:b&&(f=d,k(b))}return this},remove:function(){return i&&c.each(arguments,function(a,b){for(var d;-1<(d=c.inArray(b,i,d));)i.splice(d,1),e&&(d<=g&&g--,d<=h&&h--)}),this},has:function(a){return-1<c.inArray(a,i)},empty:function(){return i=[],this},disable:function(){return i=j=b=n,this},disabled:function(){return!i},lock:function(){return j=n,b||p.disable(),this},locked:function(){return!j},fireWith:function(a,b){return b=b||[],b=[a,b.slice?b.slice():b],
i&&(!d||j)&&(e?j.push(b):k(b)),this},fire:function(){return p.fireWith(this,arguments),this},fired:function(){return!!d}};return p};c.extend({Deferred:function(a){var b=[["resolve","done",c.Callbacks("once memory"),"resolved"],["reject","fail",c.Callbacks("once memory"),"rejected"],["notify","progress",c.Callbacks("memory")]],d="pending",e={state:function(){return d},always:function(){return f.done(arguments).fail(arguments),this},then:function(){var a=arguments;return c.Deferred(function(d){c.each(b,
function(b,e){var k=e[0],p=a[b];f[e[1]](c.isFunction(p)?function(){var a=p.apply(this,arguments);a&&c.isFunction(a.promise)?a.promise().done(d.resolve).fail(d.reject).progress(d.notify):d[k+"With"](this===f?d:this,[a])}:d[k])});a=null}).promise()},promise:function(a){return"object"==typeof a?c.extend(a,e):e}},f={};return e.pipe=e.then,c.each(b,function(a,c){var i=c[2],j=c[3];e[c[1]]=i.add;j&&i.add(function(){d=j},b[a^1][2].disable,b[2][2].lock);f[c[0]]=i.fire;f[c[0]+"With"]=i.fireWith}),e.promise(f),
a&&a.call(f,f),f},when:function(a){var b=0,d=C.call(arguments),e=d.length,f=1!==e||a&&c.isFunction(a.promise)?e:0,g=1===f?a:c.Deferred(),h=function(a,b,d){return function(c){b[a]=this;d[a]=1<arguments.length?C.call(arguments):c;d===i?g.notifyWith(b,d):--f||g.resolveWith(b,d)}},i,j,k;if(1<e){i=Array(e);j=Array(e);for(k=Array(e);b<e;b++)d[b]&&c.isFunction(d[b].promise)?d[b].promise().done(h(b,k,d)).fail(g.reject).progress(h(b,j,i)):--f}return f||g.resolveWith(k,d),g.promise()}});c.support=function(){var a,
b,d,e,f,g,h,i,j=m.createElement("div");j.setAttribute("className","t");j.innerHTML="  <link/><table></table><a href='/a'>a</a><input type='checkbox'/>";b=j.getElementsByTagName("*");d=j.getElementsByTagName("a")[0];d.style.cssText="top:1px;float:left;opacity:.5";if(!b||!b.length||!d)return{};e=m.createElement("select");f=e.appendChild(m.createElement("option"));b=j.getElementsByTagName("input")[0];a={leadingWhitespace:3===j.firstChild.nodeType,tbody:!j.getElementsByTagName("tbody").length,htmlSerialize:!!j.getElementsByTagName("link").length,
style:/top/.test(d.getAttribute("style")),hrefNormalized:"/a"===d.getAttribute("href"),opacity:/^0.5/.test(d.style.opacity),cssFloat:!!d.style.cssFloat,checkOn:"on"===b.value,optSelected:f.selected,getSetAttribute:"t"!==j.className,enctype:!!m.createElement("form").enctype,html5Clone:"<:nav></:nav>"!==m.createElement("nav").cloneNode(!0).outerHTML,boxModel:"CSS1Compat"===m.compatMode,submitBubbles:!0,changeBubbles:!0,focusinBubbles:!1,deleteExpando:!0,noCloneEvent:!0,inlineBlockNeedsLayout:!1,shrinkWrapBlocks:!1,
reliableMarginRight:!0,boxSizingReliable:!0,pixelPosition:!1};b.checked=!0;a.noCloneChecked=b.cloneNode(!0).checked;e.disabled=!0;a.optDisabled=!f.disabled;try{delete j.test}catch(k){a.deleteExpando=!1}!j.addEventListener&&j.attachEvent&&j.fireEvent&&(j.attachEvent("onclick",i=function(){a.noCloneEvent=!1}),j.cloneNode(!0).fireEvent("onclick"),j.detachEvent("onclick",i));b=m.createElement("input");b.value="t";b.setAttribute("type","radio");a.radioValue="t"===b.value;b.setAttribute("checked","checked");
b.setAttribute("name","t");j.appendChild(b);d=m.createDocumentFragment();d.appendChild(j.lastChild);a.checkClone=d.cloneNode(!0).cloneNode(!0).lastChild.checked;a.appendChecked=b.checked;d.removeChild(b);d.appendChild(j);if(j.attachEvent)for(g in{submit:!0,change:!0,focusin:!0})b="on"+g,(h=b in j)||(j.setAttribute(b,"return;"),h="function"==typeof j[b]),a[g+"Bubbles"]=h;return c(function(){var b,d,c,e,f=m.getElementsByTagName("body")[0];f&&(b=m.createElement("div"),b.style.cssText="visibility:hidden;border:0;width:0;height:0;position:static;top:0;margin-top:1px",
f.insertBefore(b,f.firstChild),d=m.createElement("div"),b.appendChild(d),d.innerHTML="<table><tr><td></td><td>t</td></tr></table>",c=d.getElementsByTagName("td"),c[0].style.cssText="padding:0;margin:0;border:0;display:none",h=0===c[0].offsetHeight,c[0].style.display="",c[1].style.display="none",a.reliableHiddenOffsets=h&&0===c[0].offsetHeight,d.innerHTML="",d.style.cssText="box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;padding:1px;border:1px;display:block;width:4px;margin-top:1%;position:absolute;top:1%;",
a.boxSizing=4===d.offsetWidth,a.doesNotIncludeMarginInBodyOffset=1!==f.offsetTop,o.getComputedStyle&&(a.pixelPosition="1%"!==(o.getComputedStyle(d,null)||{}).top,a.boxSizingReliable="4px"===(o.getComputedStyle(d,null)||{width:"4px"}).width,e=m.createElement("div"),e.style.cssText=d.style.cssText="padding:0;margin:0;border:0;display:block;overflow:hidden;",e.style.marginRight=e.style.width="0",d.style.width="1px",d.appendChild(e),a.reliableMarginRight=!parseFloat((o.getComputedStyle(e,null)||{}).marginRight)),
"undefined"!=typeof d.style.zoom&&(d.innerHTML="",d.style.cssText="padding:0;margin:0;border:0;display:block;overflow:hidden;width:1px;padding:1px;display:inline;zoom:1",a.inlineBlockNeedsLayout=3===d.offsetWidth,d.style.display="block",d.style.overflow="visible",d.innerHTML="<div></div>",d.firstChild.style.width="5px",a.shrinkWrapBlocks=3!==d.offsetWidth,b.style.zoom=1),f.removeChild(b))}),d.removeChild(j),b=d=e=f=b=d=j=null,a}();var zb=/(?:\{[\s\S]*\}|\[[\s\S]*\])$/,yb=/([A-Z])/g;c.extend({cache:{},
deletedIds:[],uuid:0,expando:"jQuery"+(c.fn.jquery+Math.random()).replace(/\D/g,""),noData:{embed:!0,object:"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000",applet:!0},hasData:function(a){return a=a.nodeType?c.cache[a[c.expando]]:a[c.expando],!!a&&!I(a)},data:function(a,b,d,e){if(c.acceptData(a)){var f,g,h=c.expando,i="string"==typeof b,j=a.nodeType,k=j?c.cache:a,p=j?a[h]:a[h]&&h;if(p&&k[p]&&(e||k[p].data)||!(i&&d===n)){p||(j?a[h]=p=c.deletedIds.pop()||++c.uuid:p=h);k[p]||(k[p]={},j||(k[p].toJSON=c.noop));
if("object"==typeof b||"function"==typeof b)e?k[p]=c.extend(k[p],b):k[p].data=c.extend(k[p].data,b);return f=k[p],e||(f.data||(f.data={}),f=f.data),d!==n&&(f[c.camelCase(b)]=d),i?(g=f[b],null==g&&(g=f[c.camelCase(b)])):g=f,g}}},removeData:function(a,b,d){if(c.acceptData(a)){var e,f,g,h=a.nodeType,i=h?c.cache:a,j=h?a[c.expando]:c.expando;if(i[j]){if(b&&(e=d?i[j]:i[j].data)){c.isArray(b)||(b in e?b=[b]:(b=c.camelCase(b),b in e?b=[b]:b=b.split(" ")));f=0;for(g=b.length;f<g;f++)delete e[b[f]];if(!(d?
I:c.isEmptyObject)(e))return}if(!d&&(delete i[j].data,!I(i[j])))return;h?c.cleanData([a],!0):c.support.deleteExpando||i!=i.window?delete i[j]:i[j]=null}}},_data:function(a,b,d){return c.data(a,b,d,!0)},acceptData:function(a){var b=a.nodeName&&c.noData[a.nodeName.toLowerCase()];return!b||!0!==b&&a.getAttribute("classid")===b}});c.fn.extend({data:function(a,b){var d,e,f,g,h,i=this[0],j=0,k=null;if(a===n){if(this.length&&(k=c.data(i),1===i.nodeType&&!c._data(i,"parsedAttrs"))){f=i.attributes;for(h=f.length;j<
h;j++)g=f[j].name,0===g.indexOf("data-")&&(g=c.camelCase(g.substring(5)),z(i,g,k[g]));c._data(i,"parsedAttrs",!0)}return k}return"object"==typeof a?this.each(function(){c.data(this,a)}):(d=a.split(".",2),d[1]=d[1]?"."+d[1]:"",e=d[1]+"!",c.access(this,function(b){if(b===n)return k=this.triggerHandler("getData"+e,[d[0]]),k===n&&i&&(k=c.data(i,a),k=z(i,a,k)),k===n&&d[1]?this.data(d[0]):k;d[1]=b;this.each(function(){var f=c(this);f.triggerHandler("setData"+e,d);c.data(this,a,b);f.triggerHandler("changeData"+
e,d)})},null,b,1<arguments.length,null,!1))},removeData:function(a){return this.each(function(){c.removeData(this,a)})}});c.extend({queue:function(a,b,d){var e;if(a)return b=(b||"fx")+"queue",e=c._data(a,b),d&&(!e||c.isArray(d)?e=c._data(a,b,c.makeArray(d)):e.push(d)),e||[]},dequeue:function(a,b){var b=b||"fx",d=c.queue(a,b),e=d.length,f=d.shift(),g=c._queueHooks(a,b),h=function(){c.dequeue(a,b)};"inprogress"===f&&(f=d.shift(),e--);f&&("fx"===b&&d.unshift("inprogress"),delete g.stop,f.call(a,h,g));
!e&&g&&g.empty.fire()},_queueHooks:function(a,b){var d=b+"queueHooks";return c._data(a,d)||c._data(a,d,{empty:c.Callbacks("once memory").add(function(){c.removeData(a,b+"queue",!0);c.removeData(a,d,!0)})})}});c.fn.extend({queue:function(a,b){var d=2;return"string"!=typeof a&&(b=a,a="fx",d--),arguments.length<d?c.queue(this[0],a):b===n?this:this.each(function(){var d=c.queue(this,a,b);c._queueHooks(this,a);"fx"===a&&"inprogress"!==d[0]&&c.dequeue(this,a)})},dequeue:function(a){return this.each(function(){c.dequeue(this,
a)})},delay:function(a,b){return a=c.fx?c.fx.speeds[a]||a:a,b=b||"fx",this.queue(b,function(b,c){var f=setTimeout(b,a);c.stop=function(){clearTimeout(f)}})},clearQueue:function(a){return this.queue(a||"fx",[])},promise:function(a,b){var d,e=1,f=c.Deferred(),g=this,h=this.length,i=function(){--e||f.resolveWith(g,[g])};"string"!=typeof a&&(b=a,a=n);for(a=a||"fx";h--;)(d=c._data(g[h],a+"queueHooks"))&&d.empty&&(e++,d.empty.add(i));return i(),f.promise(b)}});var D,Za,$a,ab=/[\t\r\n]/g,Ub=/\r/g,Vb=/^(?:button|input)$/i,
Wb=/^(?:button|input|object|select|textarea)$/i,Xb=/^a(?:rea|)$/i,bb=/^(?:autofocus|autoplay|async|checked|controls|defer|disabled|hidden|loop|multiple|open|readonly|required|scoped|selected)$/i,cb=c.support.getSetAttribute;c.fn.extend({attr:function(a,b){return c.access(this,c.attr,a,b,1<arguments.length)},removeAttr:function(a){return this.each(function(){c.removeAttr(this,a)})},prop:function(a,b){return c.access(this,c.prop,a,b,1<arguments.length)},removeProp:function(a){return a=c.propFix[a]||
a,this.each(function(){try{this[a]=n,delete this[a]}catch(b){}})},addClass:function(a){var b,d,e,f,g,h,i;if(c.isFunction(a))return this.each(function(b){c(this).addClass(a.call(this,b,this.className))});if(a&&"string"==typeof a){b=a.split(A);d=0;for(e=this.length;d<e;d++)if(f=this[d],1===f.nodeType)if(!f.className&&1===b.length)f.className=a;else{g=" "+f.className+" ";h=0;for(i=b.length;h<i;h++)~g.indexOf(" "+b[h]+" ")||(g+=b[h]+" ");f.className=c.trim(g)}}return this},removeClass:function(a){var b,
d,e,f,g,h,i;if(c.isFunction(a))return this.each(function(b){c(this).removeClass(a.call(this,b,this.className))});if(a&&"string"==typeof a||a===n){b=(a||"").split(A);h=0;for(i=this.length;h<i;h++)if(e=this[h],1===e.nodeType&&e.className){d=(" "+e.className+" ").replace(ab," ");f=0;for(g=b.length;f<g;f++)for(;-1<d.indexOf(" "+b[f]+" ");)d=d.replace(" "+b[f]+" "," ");e.className=a?c.trim(d):""}}return this},toggleClass:function(a,b){var d=typeof a,e="boolean"==typeof b;return c.isFunction(a)?this.each(function(d){c(this).toggleClass(a.call(this,
d,this.className,b),b)}):this.each(function(){if("string"===d)for(var f,g=0,h=c(this),i=b,j=a.split(A);f=j[g++];)i=e?i:!h.hasClass(f),h[i?"addClass":"removeClass"](f);else if("undefined"===d||"boolean"===d)this.className&&c._data(this,"__className__",this.className),this.className=this.className||!1===a?"":c._data(this,"__className__")||""})},hasClass:function(a){for(var a=" "+a+" ",b=0,d=this.length;b<d;b++)if(1===this[b].nodeType&&-1<(" "+this[b].className+" ").replace(ab," ").indexOf(a))return!0;
return!1},val:function(a){var b,d,e,f=this[0];if(arguments.length)return e=c.isFunction(a),this.each(function(d){var f,i=c(this);if(1===this.nodeType&&(e?f=a.call(this,d,i.val()):f=a,null==f?f="":"number"==typeof f?f+="":c.isArray(f)&&(f=c.map(f,function(a){return a==null?"":a+""})),b=c.valHooks[this.type]||c.valHooks[this.nodeName.toLowerCase()],!b||!("set"in b)||b.set(this,f,"value")===n))this.value=f});if(f)return b=c.valHooks[f.type]||c.valHooks[f.nodeName.toLowerCase()],b&&"get"in b&&(d=b.get(f,
"value"))!==n?d:(d=f.value,"string"==typeof d?d.replace(Ub,""):null==d?"":d)}});c.extend({valHooks:{option:{get:function(a){var b=a.attributes.value;return!b||b.specified?a.value:a.text}},select:{get:function(a){var b,d,e=a.selectedIndex,f=[],g=a.options,h="select-one"===a.type;if(0>e)return null;a=h?e:0;for(d=h?e+1:g.length;a<d;a++)if(b=g[a],b.selected&&(c.support.optDisabled?!b.disabled:null===b.getAttribute("disabled"))&&(!b.parentNode.disabled||!c.nodeName(b.parentNode,"optgroup"))){b=c(b).val();
if(h)return b;f.push(b)}return h&&!f.length&&g.length?c(g[e]).val():f},set:function(a,b){var d=c.makeArray(b);return c(a).find("option").each(function(){this.selected=0<=c.inArray(c(this).val(),d)}),d.length||(a.selectedIndex=-1),d}}},attrFn:{},attr:function(a,b,d,e){var f,g,h=a.nodeType;if(a&&!(3===h||8===h||2===h)){if(e&&c.isFunction(c.fn[b]))return c(a)[b](d);if("undefined"==typeof a.getAttribute)return c.prop(a,b,d);(e=1!==h||!c.isXMLDoc(a))&&(b=b.toLowerCase(),g=c.attrHooks[b]||(bb.test(b)?Za:
D));if(d!==n){if(null===d){c.removeAttr(a,b);return}return g&&"set"in g&&e&&(f=g.set(a,d,b))!==n?f:(a.setAttribute(b,""+d),d)}return g&&"get"in g&&e&&null!==(f=g.get(a,b))?f:(f=a.getAttribute(b),null===f?n:f)}},removeAttr:function(a,b){var d,e,f,g,h=0;if(b&&1===a.nodeType)for(e=b.split(A);h<e.length;h++)(f=e[h])&&(d=c.propFix[f]||f,g=bb.test(f),g||c.attr(a,f,""),a.removeAttribute(cb?f:d),g&&d in a&&(a[d]=!1))},attrHooks:{type:{set:function(a,b){if(Vb.test(a.nodeName)&&a.parentNode)c.error("type property can't be changed");
else if(!c.support.radioValue&&"radio"===b&&c.nodeName(a,"input")){var d=a.value;return a.setAttribute("type",b),d&&(a.value=d),b}}},value:{get:function(a,b){return D&&c.nodeName(a,"button")?D.get(a,b):b in a?a.value:null},set:function(a,b,d){if(D&&c.nodeName(a,"button"))return D.set(a,b,d);a.value=b}}},propFix:{tabindex:"tabIndex",readonly:"readOnly","for":"htmlFor","class":"className",maxlength:"maxLength",cellspacing:"cellSpacing",cellpadding:"cellPadding",rowspan:"rowSpan",colspan:"colSpan",usemap:"useMap",
frameborder:"frameBorder",contenteditable:"contentEditable"},prop:function(a,b,d){var e,f,g,h=a.nodeType;return!a||3===h||8===h||2===h?void 0:(g=1!==h||!c.isXMLDoc(a),g&&(b=c.propFix[b]||b,f=c.propHooks[b]),d!==n?f&&"set"in f&&(e=f.set(a,d,b))!==n?e:a[b]=d:f&&"get"in f&&null!==(e=f.get(a,b))?e:a[b])},propHooks:{tabIndex:{get:function(a){var b=a.getAttributeNode("tabindex");return b&&b.specified?parseInt(b.value,10):Wb.test(a.nodeName)||Xb.test(a.nodeName)&&a.href?0:n}}}});Za={get:function(a,b){var d,
e=c.prop(a,b);return!0===e||"boolean"!=typeof e&&(d=a.getAttributeNode(b))&&!1!==d.nodeValue?b.toLowerCase():n},set:function(a,b,d){var e;return!1===b?c.removeAttr(a,d):(e=c.propFix[d]||d,e in a&&(a[e]=!0),a.setAttribute(d,d.toLowerCase())),d}};cb||($a={name:!0,id:!0,coords:!0},D=c.valHooks.button={get:function(a,b){var d;return d=a.getAttributeNode(b),d&&($a[b]?""!==d.value:d.specified)?d.value:n},set:function(a,b,d){var c=a.getAttributeNode(d);return c||(c=m.createAttribute(d),a.setAttributeNode(c)),
c.value=b+""}},c.each(["width","height"],function(a,b){c.attrHooks[b]=c.extend(c.attrHooks[b],{set:function(a,c){if(""===c)return a.setAttribute(b,"auto"),c}})}),c.attrHooks.contenteditable={get:D.get,set:function(a,b,d){""===b&&(b="false");D.set(a,b,d)}});c.support.hrefNormalized||c.each(["href","src","width","height"],function(a,b){c.attrHooks[b]=c.extend(c.attrHooks[b],{get:function(a){a=a.getAttribute(b,2);return null===a?n:a}})});c.support.style||(c.attrHooks.style={get:function(a){return a.style.cssText.toLowerCase()||
n},set:function(a,b){return a.style.cssText=""+b}});c.support.optSelected||(c.propHooks.selected=c.extend(c.propHooks.selected,{get:function(a){a=a.parentNode;return a&&(a.selectedIndex,a.parentNode&&a.parentNode.selectedIndex),null}}));c.support.enctype||(c.propFix.enctype="encoding");c.support.checkOn||c.each(["radio","checkbox"],function(){c.valHooks[this]={get:function(a){return null===a.getAttribute("value")?"on":a.value}}});c.each(["radio","checkbox"],function(){c.valHooks[this]=c.extend(c.valHooks[this],
{set:function(a,b){if(c.isArray(b))return a.checked=0<=c.inArray(c(a).val(),b)}})});var sa=/^(?:textarea|input|select)$/i,db=/^([^\.]*|)(?:\.(.+)|)$/,Yb=/(?:^|\s)hover(\.\S+|)\b/,Zb=/^key/,$b=/^(?:mouse|contextmenu)|click/,eb=/^(?:focusinfocus|focusoutblur)$/,fb=function(a){return c.event.special.hover?a:a.replace(Yb,"mouseenter$1 mouseleave$1")};c.event={add:function(a,b,d,e,f){var g,h,i,j,k,p,l,m,v;if(!(3===a.nodeType||8===a.nodeType||!b||!d||!(g=c._data(a)))){d.handler&&(l=d,d=l.handler,f=l.selector);
d.guid||(d.guid=c.guid++);(i=g.events)||(g.events=i={});(h=g.handle)||(g.handle=h=function(a){return"undefined"!=typeof c&&(!a||c.event.triggered!==a.type)?c.event.dispatch.apply(h.elem,arguments):n},h.elem=a);b=c.trim(fb(b)).split(" ");for(g=0;g<b.length;g++){j=db.exec(b[g])||[];k=j[1];p=(j[2]||"").split(".").sort();v=c.event.special[k]||{};k=(f?v.delegateType:v.bindType)||k;v=c.event.special[k]||{};j=c.extend({type:k,origType:j[1],data:e,handler:d,guid:d.guid,selector:f,namespace:p.join(".")},l);
m=i[k];if(!m&&(m=i[k]=[],m.delegateCount=0,!v.setup||!1===v.setup.call(a,e,p,h)))a.addEventListener?a.addEventListener(k,h,!1):a.attachEvent&&a.attachEvent("on"+k,h);v.add&&(v.add.call(a,j),j.handler.guid||(j.handler.guid=d.guid));f?m.splice(m.delegateCount++,0,j):m.push(j);c.event.global[k]=!0}a=null}},global:{},remove:function(a,b,d,e,f){var g,h,i,j,k,p,l,n,m,o,t=c.hasData(a)&&c._data(a);if(t&&(l=t.events)){b=c.trim(fb(b||"")).split(" ");for(g=0;g<b.length;g++)if(h=db.exec(b[g])||[],i=j=h[1],h=
h[2],i){n=c.event.special[i]||{};i=(e?n.delegateType:n.bindType)||i;m=l[i]||[];k=m.length;h=h?RegExp("(^|\\.)"+h.split(".").sort().join("\\.(?:.*\\.|)")+"(\\.|$)"):null;for(p=0;p<m.length;p++)o=m[p],(f||j===o.origType)&&(!d||d.guid===o.guid)&&(!h||h.test(o.namespace))&&(!e||e===o.selector||"**"===e&&o.selector)&&(m.splice(p--,1),o.selector&&m.delegateCount--,n.remove&&n.remove.call(a,o));0===m.length&&k!==m.length&&((!n.teardown||!1===n.teardown.call(a,h,t.handle))&&c.removeEvent(a,i,t.handle),delete l[i])}else for(i in l)c.event.remove(a,
i+b[g],d,e,!0);c.isEmptyObject(l)&&(delete t.handle,c.removeData(a,"events",!0))}},customEvent:{getData:!0,setData:!0,changeData:!0},trigger:function(a,b,d,e){if(!d||3!==d.nodeType&&8!==d.nodeType){var f,g,h,i,j,k,p,l=a.type||a;i=[];if(!eb.test(l+c.event.triggered)&&(0<=l.indexOf("!")&&(l=l.slice(0,-1),f=!0),0<=l.indexOf(".")&&(i=l.split("."),l=i.shift(),i.sort()),d&&!c.event.customEvent[l]||c.event.global[l]))if(a="object"==typeof a?a[c.expando]?a:new c.Event(l,a):new c.Event(l),a.type=l,a.isTrigger=
!0,a.exclusive=f,a.namespace=i.join("."),a.namespace_re=a.namespace?RegExp("(^|\\.)"+i.join("\\.(?:.*\\.|)")+"(\\.|$)"):null,i=0>l.indexOf(":")?"on"+l:"",d){if(a.result=n,a.target||(a.target=d),b=null!=b?c.makeArray(b):[],b.unshift(a),j=c.event.special[l]||{},!(j.trigger&&!1===j.trigger.apply(d,b))){p=[[d,j.bindType||l]];if(!e&&!j.noBubble&&!c.isWindow(d)){g=j.delegateType||l;f=eb.test(g+l)?d:d.parentNode;for(h=d;f;f=f.parentNode)p.push([f,g]),h=f;h===(d.ownerDocument||m)&&p.push([h.defaultView||
h.parentWindow||o,g])}for(g=0;g<p.length&&!a.isPropagationStopped();g++)f=p[g][0],a.type=p[g][1],(k=(c._data(f,"events")||{})[a.type]&&c._data(f,"handle"))&&k.apply(f,b),(k=i&&f[i])&&c.acceptData(f)&&!1===k.apply(f,b)&&a.preventDefault();return a.type=l,!e&&!a.isDefaultPrevented()&&(!j._default||!1===j._default.apply(d.ownerDocument,b))&&("click"!==l||!c.nodeName(d,"a"))&&c.acceptData(d)&&i&&d[l]&&("focus"!==l&&"blur"!==l||0!==a.target.offsetWidth)&&!c.isWindow(d)&&(h=d[i],h&&(d[i]=null),c.event.triggered=
l,d[l](),c.event.triggered=n,h&&(d[i]=h)),a.result}}else for(g in d=c.cache,d)d[g].events&&d[g].events[l]&&c.event.trigger(a,b,d[g].handle.elem,!0)}},dispatch:function(a){var a=c.event.fix(a||o.event),b,d,e,f,g,h,i=(c._data(this,"events")||{})[a.type]||[],j=i.delegateCount,k=[].slice.call(arguments),p=!a.exclusive&&!a.namespace,l=c.event.special[a.type]||{},m=[];k[0]=a;a.delegateTarget=this;if(!(l.preDispatch&&!1===l.preDispatch.call(this,a))){if(j&&(!a.button||"click"!==a.type))for(d=a.target;d!=
this;d=d.parentNode||this)if(!0!==d.disabled||"click"!==a.type){f={};g=[];for(b=0;b<j;b++)e=i[b],h=e.selector,f[h]===n&&(f[h]=0<=c(h,this).index(d)),f[h]&&g.push(e);g.length&&m.push({elem:d,matches:g})}i.length>j&&m.push({elem:this,matches:i.slice(j)});for(b=0;b<m.length&&!a.isPropagationStopped();b++){f=m[b];a.currentTarget=f.elem;for(d=0;d<f.matches.length&&!a.isImmediatePropagationStopped();d++)if(e=f.matches[d],p||!a.namespace&&!e.namespace||a.namespace_re&&a.namespace_re.test(e.namespace))a.data=
e.data,a.handleObj=e,e=((c.event.special[e.origType]||{}).handle||e.handler).apply(f.elem,k),e!==n&&(a.result=e,!1===e&&(a.preventDefault(),a.stopPropagation()))}return l.postDispatch&&l.postDispatch.call(this,a),a.result}},props:"attrChange,attrName,relatedNode,srcElement,altKey,bubbles,cancelable,ctrlKey,currentTarget,eventPhase,metaKey,relatedTarget,shiftKey,target,timeStamp,view,which".split(","),fixHooks:{},keyHooks:{props:["char","charCode","key","keyCode"],filter:function(a,b){return null==
a.which&&(a.which=null!=b.charCode?b.charCode:b.keyCode),a}},mouseHooks:{props:"button,buttons,clientX,clientY,fromElement,offsetX,offsetY,pageX,pageY,screenX,screenY,toElement".split(","),filter:function(a,b){var d,c,f,g=b.button,h=b.fromElement;return null==a.pageX&&null!=b.clientX&&(d=a.target.ownerDocument||m,c=d.documentElement,f=d.body,a.pageX=b.clientX+(c&&c.scrollLeft||f&&f.scrollLeft||0)-(c&&c.clientLeft||f&&f.clientLeft||0),a.pageY=b.clientY+(c&&c.scrollTop||f&&f.scrollTop||0)-(c&&c.clientTop||
f&&f.clientTop||0)),!a.relatedTarget&&h&&(a.relatedTarget=h===a.target?b.toElement:h),!a.which&&g!==n&&(a.which=g&1?1:g&2?3:g&4?2:0),a}},fix:function(a){if(a[c.expando])return a;var b,d,e=a,f=c.event.fixHooks[a.type]||{},g=f.props?this.props.concat(f.props):this.props,a=c.Event(e);for(b=g.length;b;)d=g[--b],a[d]=e[d];return a.target||(a.target=e.srcElement||m),3===a.target.nodeType&&(a.target=a.target.parentNode),a.metaKey=!!a.metaKey,f.filter?f.filter(a,e):a},special:{load:{noBubble:!0},focus:{delegateType:"focusin"},
blur:{delegateType:"focusout"},beforeunload:{setup:function(a,b,d){c.isWindow(this)&&(this.onbeforeunload=d)},teardown:function(a,b){this.onbeforeunload===b&&(this.onbeforeunload=null)}}},simulate:function(a,b,d,e){a=c.extend(new c.Event,d,{type:a,isSimulated:!0,originalEvent:{}});e?c.event.trigger(a,null,b):c.event.dispatch.call(b,a);a.isDefaultPrevented()&&d.preventDefault()}};c.event.handle=c.event.dispatch;c.removeEvent=m.removeEventListener?function(a,b,c){a.removeEventListener&&a.removeEventListener(b,
c,!1)}:function(a,b,c){b="on"+b;a.detachEvent&&("undefined"==typeof a[b]&&(a[b]=null),a.detachEvent(b,c))};c.Event=function(a,b){if(this instanceof c.Event)a&&a.type?(this.originalEvent=a,this.type=a.type,this.isDefaultPrevented=a.defaultPrevented||!1===a.returnValue||a.getPreventDefault&&a.getPreventDefault()?Y:u):this.type=a,b&&c.extend(this,b),this.timeStamp=a&&a.timeStamp||c.now(),this[c.expando]=!0;else return new c.Event(a,b)};c.Event.prototype={preventDefault:function(){this.isDefaultPrevented=
Y;var a=this.originalEvent;a&&(a.preventDefault?a.preventDefault():a.returnValue=!1)},stopPropagation:function(){this.isPropagationStopped=Y;var a=this.originalEvent;a&&(a.stopPropagation&&a.stopPropagation(),a.cancelBubble=!0)},stopImmediatePropagation:function(){this.isImmediatePropagationStopped=Y;this.stopPropagation()},isDefaultPrevented:u,isPropagationStopped:u,isImmediatePropagationStopped:u};c.each({mouseenter:"mouseover",mouseleave:"mouseout"},function(a,b){c.event.special[a]={delegateType:b,
bindType:b,handle:function(a){var e,f=a.relatedTarget,g=a.handleObj;if(!f||f!==this&&!c.contains(this,f))a.type=g.origType,e=g.handler.apply(this,arguments),a.type=b;return e}}});c.support.submitBubbles||(c.event.special.submit={setup:function(){if(c.nodeName(this,"form"))return!1;c.event.add(this,"click._submit keypress._submit",function(a){a=a.target;(a=c.nodeName(a,"input")||c.nodeName(a,"button")?a.form:n)&&!c._data(a,"_submit_attached")&&(c.event.add(a,"submit._submit",function(a){a._submit_bubble=
!0}),c._data(a,"_submit_attached",!0))})},postDispatch:function(a){a._submit_bubble&&(delete a._submit_bubble,this.parentNode&&!a.isTrigger&&c.event.simulate("submit",this.parentNode,a,!0))},teardown:function(){if(c.nodeName(this,"form"))return!1;c.event.remove(this,"._submit")}});c.support.changeBubbles||(c.event.special.change={setup:function(){if(sa.test(this.nodeName)){if("checkbox"===this.type||"radio"===this.type)c.event.add(this,"propertychange._change",function(a){"checked"===a.originalEvent.propertyName&&
(this._just_changed=!0)}),c.event.add(this,"click._change",function(a){this._just_changed&&!a.isTrigger&&(this._just_changed=!1);c.event.simulate("change",this,a,!0)});return!1}c.event.add(this,"beforeactivate._change",function(a){a=a.target;sa.test(a.nodeName)&&!c._data(a,"_change_attached")&&(c.event.add(a,"change._change",function(a){this.parentNode&&!a.isSimulated&&!a.isTrigger&&c.event.simulate("change",this.parentNode,a,!0)}),c._data(a,"_change_attached",!0))})},handle:function(a){var b=a.target;
if(this!==b||a.isSimulated||a.isTrigger||"radio"!==b.type&&"checkbox"!==b.type)return a.handleObj.handler.apply(this,arguments)},teardown:function(){return c.event.remove(this,"._change"),!sa.test(this.nodeName)}});c.support.focusinBubbles||c.each({focus:"focusin",blur:"focusout"},function(a,b){var d=0,e=function(a){c.event.simulate(b,a.target,c.event.fix(a),!0)};c.event.special[b]={setup:function(){0===d++&&m.addEventListener(a,e,!0)},teardown:function(){0===--d&&m.removeEventListener(a,e,!0)}}});
c.fn.extend({on:function(a,b,d,e,f){var g,h;if("object"==typeof a){"string"!=typeof b&&(d=d||b,b=n);for(h in a)this.on(h,b,d,a[h],f);return this}null==d&&null==e?(e=b,d=b=n):null==e&&("string"==typeof b?(e=d,d=n):(e=d,d=b,b=n));if(!1===e)e=u;else if(!e)return this;return 1===f&&(g=e,e=function(a){return c().off(a),g.apply(this,arguments)},e.guid=g.guid||(g.guid=c.guid++)),this.each(function(){c.event.add(this,a,e,d,b)})},one:function(a,b,c,e){return this.on(a,b,c,e,1)},off:function(a,b,d){var e,f;
if(a&&a.preventDefault&&a.handleObj)return e=a.handleObj,c(a.delegateTarget).off(e.namespace?e.origType+"."+e.namespace:e.origType,e.selector,e.handler),this;if("object"==typeof a){for(f in a)this.off(f,b,a[f]);return this}if(!1===b||"function"==typeof b)d=b,b=n;return!1===d&&(d=u),this.each(function(){c.event.remove(this,a,d,b)})},bind:function(a,b,c){return this.on(a,null,b,c)},unbind:function(a,b){return this.off(a,null,b)},live:function(a,b,d){return c(this.context).on(a,this.selector,b,d),this},
die:function(a,b){return c(this.context).off(a,this.selector||"**",b),this},delegate:function(a,b,c,e){return this.on(b,a,c,e)},undelegate:function(a,b,c){return 1==arguments.length?this.off(a,"**"):this.off(b,a||"**",c)},trigger:function(a,b){return this.each(function(){c.event.trigger(a,b,this)})},triggerHandler:function(a,b){if(this[0])return c.event.trigger(a,b,this[0],!0)},toggle:function(a){var b=arguments,d=a.guid||c.guid++,e=0,f=function(d){var f=(c._data(this,"lastToggle"+a.guid)||0)%e;return c._data(this,
"lastToggle"+a.guid,f+1),d.preventDefault(),b[f].apply(this,arguments)||!1};for(f.guid=d;e<b.length;)b[e++].guid=d;return this.click(f)},hover:function(a,b){return this.mouseenter(a).mouseleave(b||a)}});c.each("blur,focus,focusin,focusout,load,resize,scroll,unload,click,dblclick,mousedown,mouseup,mousemove,mouseover,mouseout,mouseenter,mouseleave,change,select,submit,keydown,keypress,keyup,error,contextmenu".split(","),function(a,b){c.fn[b]=function(a,c){return c==null&&(c=a,a=null),arguments.length>
0?this.on(b,null,a,c):this.trigger(b)};Zb.test(b)&&(c.event.fixHooks[b]=c.event.keyHooks);$b.test(b)&&(c.event.fixHooks[b]=c.event.mouseHooks)});(function(a,b){function d(a,b,c,d){var c=c||[],b=b||J,e,f,g,h,i=b.nodeType;if(1!==i&&9!==i)return[];if(!a||"string"!=typeof a)return c;g=ja(b);if(!g&&!d&&(e=N.exec(a)))if(h=e[1])if(9===i){f=b.getElementById(h);if(!f||!f.parentNode)return c;if(f.id===h)return c.push(f),c}else{if(b.ownerDocument&&(f=b.ownerDocument.getElementById(h))&&x(b,f)&&f.id===h)return c.push(f),
c}else{if(e[2])return X.apply(c,K.call(b.getElementsByTagName(a),0)),c;if((h=e[3])&&P&&b.getElementsByClassName)return X.apply(c,K.call(b.getElementsByClassName(h),0)),c}return o(a,b,c,d,g)}function e(a){return function(b){return"input"===b.nodeName.toLowerCase()&&b.type===a}}function f(a){return function(b){var c=b.nodeName.toLowerCase();return("input"===c||"button"===c)&&b.type===a}}function g(a,b,c){if(a===b)return c;for(a=a.nextSibling;a;){if(a===b)return-1;a=a.nextSibling}return 1}function h(a,
b,c,e){var f,g,h,i,j,l,k,n,p,m=!c&&b!==J,o=(m?"<s>":"")+a.replace(D,"$1<s>");if(j=gb[E][o])return e?0:K.call(j,0);j=a;l=[];n=s.preFilter;for(p=s.filter;j;){if(!f||(g=ac.exec(j)))g&&(j=j.slice(g[0].length),h.selector=k),l.push(h=[]),k="",m&&(j=" "+j);f=!1;if(g=A.exec(j))k+=g[0],j=j.slice(g[0].length),f=h.push({part:g.pop().replace(D," "),string:g[0],captures:g});for(i in p)(g=S[i].exec(j))&&(!n[i]||(g=n[i](g,b,c)))&&(k+=g[0],j=j.slice(g[0].length),f=h.push({part:i,string:g.shift(),captures:g}));if(!f)break}return k&&
(h.selector=k),e?j.length:j?d.error(a):K.call(gb(o,l),0)}function i(a,b,c,d){var e=b.dir,f=hb++;return a||(a=function(a){return a===c}),b.first?function(b){for(;b=b[e];)if(1===b.nodeType)return a(b)&&b}:d?function(b){for(;b=b[e];)if(1===b.nodeType&&a(b))return b}:function(b){for(var c,d=f+"."+t,g=d+"."+r;b=b[e];)if(1===b.nodeType){if((c=b[E])===g)return b.sizset;if("string"==typeof c&&0===c.indexOf(d)){if(b.sizset)return b}else{b[E]=g;if(a(b))return b.sizset=!0,b;b.sizset=!1}}}}function j(a,b){return a?
function(c){var d=b(c);return d&&a(!0===d?c:d)}:b}function k(a){return function(b){for(var c,d=0;c=a[d];d++)if(c(b))return!0;return!1}}function n(a,b,c,e){for(var f=0,g=b.length;f<g;f++)d(a,b[f],c,e)}function l(a,b,c,e,f,g){var h,i=s.setFilters[b.toLowerCase()];return i||d.error(b),(a||!(h=f))&&n(a||"*",e,h=[],f),0<h.length?i(h,c,g):[]}function m(a,c,e,f){for(var g,h,i,j,k,o,q,v,E,L,t,ra=0,s=a.length,J=S.POS,K=RegExp("^"+J.source+"(?!"+w+")","i"),y=function(){for(var a=1,c=arguments.length-2;a<c;a++)arguments[a]===
b&&(v[a]=b)};ra<s;ra++){g=a[ra];h="";q=f;i=0;for(j=g.length;i<j;i++){k=g[i];o=k.string;if("PSEUDO"===k.part){J.exec("");for(k=0;v=J.exec(o);){E=!0;L=J.lastIndex=v.index+v[0].length;if(L>k){h+=o.slice(k,v.index);k=L;L=[c];A.test(h)&&(q&&(L=q),q=f);if(t=O.test(h))h=h.slice(0,-5).replace(A,"$&*"),k++;1<v.length&&v[0].replace(K,y);q=l(h,v[1],v[2],L,q,t)}h=""}}E||(h+=o);E=!1}h?A.test(h)?n(h,q||[c],e,f):d(h,c,e,f?f.concat(q):q):X.apply(e,q)}return 1===s?e:d.uniqueSort(e)}function o(a,b,c,d,e){var a=a.replace(D,
"$1"),f,g,i,j,k,l;g=h(a,b,e);k=b.nodeType;if(S.POS.test(a))return m(g,b,c,d);if(d)f=K.call(d,0);else if(1===g.length){if(2<(i=K.call(g[0],0)).length&&"ID"===(j=i[0]).part&&9===k&&!e&&s.relative[i[1].part]){b=s.find.ID(j.captures[0].replace(W,""),b,e)[0];if(!b)return c;a=a.slice(i.shift().string.length)}d=(g=H.exec(i[0].string))&&!g.index&&b.parentNode||b;k="";for(g=i.length-1;0<=g;g--){j=i[g];l=j.part;k=j.string+k;if(s.relative[l])break;if(s.order.test(l)&&(f=s.find[l](j.captures[0].replace(W,""),
d,e),null!=f)){(a=a.slice(0,a.length-k.length)+k.replace(S[l],""))||X.apply(c,K.call(f,0));break}}}if(a){e=q(a,b,e);t=e.dirruns++;null==f&&(f=s.find.TAG("*",H.test(a)&&b.parentNode||b));for(g=0;a=f[g];g++)r=e.runs++,e(a)&&c.push(a)}return c}var t,r,z,s,B,ja,x,q,I,u,L=!0,E=("sizcache"+Math.random()).replace(".",""),J=a.document,M=J.documentElement,hb=0,K=[].slice,X=[].push,Z=function(a,b){return a[E]=b||!0,a},y=function(){var a={},b=[];return Z(function(c,d){return b.push(c)>s.cacheLength&&delete a[b.shift()],
a[c]=d},a)},ib=y(),gb=y(),F=y(),w="[\\x20\\t\\r\\n\\f]",y="(?:\\\\.|[-\\w]|[^\\x00-\\xa0])+".replace("w","w#"),y="\\["+w+"*((?:\\\\.|[-\\w]|[^\\x00-\\xa0])+)"+w+"*(?:([*^$|!~]?=)"+w+"*(?:(['\"])((?:\\\\.|[^\\\\])*?)\\3|("+y+")|)|)"+w+"*\\]",C=":((?:\\\\.|[-\\w]|[^\\x00-\\xa0])+)(?:\\((?:(['\"])((?:\\\\.|[^\\\\])*?)\\2|([^()[\\]]*|(?:(?:"+y+")|[^:]|\\\\.)*|.*))\\)|)",D=RegExp("^"+w+"+|((?:^|[^\\\\])(?:\\\\.)*)"+w+"+$","g"),ac=RegExp("^"+w+"*,"+w+"*"),A=RegExp("^"+w+"*([\\x20\\t\\r\\n\\f>+~])"+w+"*"),
G=RegExp(C),N=/^(?:#([\w\-]+)|(\w+)|\.([\w\-]+))$/,H=/[\x20\t\r\n\f]*[+~]/,O=/:not\($/,Q=/h\d/i,R=/input|select|textarea|button/i,W=/\\(?!\\)/g,S={ID:/^#((?:\\.|[-\w]|[^\x00-\xa0])+)/,CLASS:/^\.((?:\\.|[-\w]|[^\x00-\xa0])+)/,NAME:/^\[name=['"]?((?:\\.|[-\w]|[^\x00-\xa0])+)['"]?\]/,TAG:RegExp("^("+"(?:\\\\.|[-\\w]|[^\\x00-\\xa0])+".replace("w","w*")+")"),ATTR:RegExp("^"+y),PSEUDO:RegExp("^"+C),CHILD:RegExp("^:(only|nth|last|first)-child(?:\\("+w+"*(even|odd|(([+-]|)(\\d*)n|)"+w+"*(?:([+-]|)"+w+"*(\\d+)|))"+
w+"*\\)|)","i"),POS:RegExp(":(nth|eq|gt|lt|first|last|even|odd)(?:\\(((?:-\\d)?\\d*)\\)|)(?=[^-]|$)","ig"),needsContext:RegExp("^"+w+"*[>+~]|:(nth|eq|gt|lt|first|last|even|odd)(?:\\(((?:-\\d)?\\d*)\\)|)(?=[^-]|$)","i")},T=function(a){var b=J.createElement("div");try{return a(b)}catch(c){return!1}finally{}},y=T(function(a){return a.appendChild(J.createComment("")),!a.getElementsByTagName("*").length}),C=T(function(a){return a.innerHTML="<a href='#'></a>",a.firstChild&&"undefined"!==typeof a.firstChild.getAttribute&&
"#"===a.firstChild.getAttribute("href")}),U=T(function(a){a.innerHTML="<select></select>";a=typeof a.lastChild.getAttribute("multiple");return"boolean"!==a&&"string"!==a}),P=T(function(a){return a.innerHTML="<div class='hidden e'></div><div class='hidden'></div>",!a.getElementsByClassName||!a.getElementsByClassName("e").length?!1:(a.lastChild.className="e",2===a.getElementsByClassName("e").length)}),V=T(function(a){a.id=E+0;a.innerHTML="<a name='"+E+"'></a><div name='"+E+"'></div>";M.insertBefore(a,
M.firstChild);var b=J.getElementsByName&&J.getElementsByName(E).length===2+J.getElementsByName(E+0).length;return z=!J.getElementById(E),M.removeChild(a),b});try{K.call(M.childNodes,0)[0].nodeType}catch(Y){K=function(a){for(var b,c=[];b=this[a];a++)c.push(b);return c}}d.matches=function(a,b){return d(a,null,null,b)};d.matchesSelector=function(a,b){return 0<d(b,null,null,[a]).length};B=d.getText=function(a){var b,c="",d=0;if(b=a.nodeType)if(1===b||9===b||11===b){if("string"==typeof a.textContent)return a.textContent;
for(a=a.firstChild;a;a=a.nextSibling)c+=B(a)}else{if(3===b||4===b)return a.nodeValue}else for(;b=a[d];d++)c+=B(b);return c};ja=d.isXML=function(a){return(a=a&&(a.ownerDocument||a).documentElement)?"HTML"!==a.nodeName:!1};x=d.contains=M.contains?function(a,b){var c=9===a.nodeType?a.documentElement:a,d=b&&b.parentNode;return a===d||!(!d||!(1===d.nodeType&&c.contains&&c.contains(d)))}:M.compareDocumentPosition?function(a,b){return b&&!!(a.compareDocumentPosition(b)&16)}:function(a,b){for(;b=b.parentNode;)if(b===
a)return!0;return!1};d.attr=function(a,b){var c,d=ja(a);return d||(b=b.toLowerCase()),s.attrHandle[b]?s.attrHandle[b](a):U||d?a.getAttribute(b):(c=a.getAttributeNode(b),c?"boolean"==typeof a[b]?a[b]?b:null:c.specified?c.value:null:null)};s=d.selectors={cacheLength:50,createPseudo:Z,match:S,order:RegExp("ID|TAG"+(V?"|NAME":"")+(P?"|CLASS":"")),attrHandle:C?{}:{href:function(a){return a.getAttribute("href",2)},type:function(a){return a.getAttribute("type")}},find:{ID:z?function(a,b,c){if("undefined"!==
typeof b.getElementById&&!c)return(a=b.getElementById(a))&&a.parentNode?[a]:[]}:function(a,c,d){if("undefined"!==typeof c.getElementById&&!d)return(c=c.getElementById(a))?c.id===a||"undefined"!==typeof c.getAttributeNode&&c.getAttributeNode("id").value===a?[c]:b:[]},TAG:y?function(a,b){if("undefined"!==typeof b.getElementsByTagName)return b.getElementsByTagName(a)}:function(a,b){var c=b.getElementsByTagName(a);if("*"===a){for(var d,e=[],f=0;d=c[f];f++)1===d.nodeType&&e.push(d);return e}return c},
NAME:function(a,b){if("undefined"!==typeof b.getElementsByName)return b.getElementsByName(name)},CLASS:function(a,b,c){if("undefined"!==typeof b.getElementsByClassName&&!c)return b.getElementsByClassName(a)}},relative:{">":{dir:"parentNode",first:!0}," ":{dir:"parentNode"},"+":{dir:"previousSibling",first:!0},"~":{dir:"previousSibling"}},preFilter:{ATTR:function(a){return a[1]=a[1].replace(W,""),a[3]=(a[4]||a[5]||"").replace(W,""),"~="===a[2]&&(a[3]=" "+a[3]+" "),a.slice(0,4)},CHILD:function(a){return a[1]=
a[1].toLowerCase(),"nth"===a[1]?(a[2]||d.error(a[0]),a[3]=+(a[3]?a[4]+(a[5]||1):2*("even"===a[2]||"odd"===a[2])),a[4]=+(a[6]+a[7]||"odd"===a[2])):a[2]&&d.error(a[0]),a},PSEUDO:function(a,b,c){var d,e;if(S.CHILD.test(a[0]))return null;if(a[3])a[2]=a[3];else if(d=a[4])G.test(d)&&(e=h(d,b,c,!0))&&(e=d.indexOf(")",d.length-e)-d.length)&&(d=d.slice(0,e),a[0]=a[0].slice(0,e)),a[2]=d;return a.slice(0,3)}},filter:{ID:z?function(a){return a=a.replace(W,""),function(b){return b.getAttribute("id")===a}}:function(a){return a=
a.replace(W,""),function(b){return(b="undefined"!==typeof b.getAttributeNode&&b.getAttributeNode("id"))&&b.value===a}},TAG:function(a){return"*"===a?function(){return!0}:(a=a.replace(W,"").toLowerCase(),function(b){return b.nodeName&&b.nodeName.toLowerCase()===a})},CLASS:function(a){var b=ib[E][a];return b||(b=ib(a,RegExp("(^|"+w+")"+a+"("+w+"|$)"))),function(a){return b.test(a.className||"undefined"!==typeof a.getAttribute&&a.getAttribute("class")||"")}},ATTR:function(a,b,c){return b?function(e){var e=
d.attr(e,a),f=e+"";if(null==e)return"!="===b;switch(b){case "=":return f===c;case "!=":return f!==c;case "^=":return c&&0===f.indexOf(c);case "*=":return c&&-1<f.indexOf(c);case "$=":return c&&f.substr(f.length-c.length)===c;case "~=":return-1<(" "+f+" ").indexOf(c);case "|=":return f===c||f.substr(0,c.length+1)===c+"-"}}:function(b){return null!=d.attr(b,a)}},CHILD:function(a,b,c,d){if("nth"===a){var e=hb++;return function(a){var b,f,g=0,h=a;if(1===c&&0===d)return!0;if((b=a.parentNode)&&(b[E]!==
e||!a.sizset)){for(h=b.firstChild;h&&!(1===h.nodeType&&(h.sizset=++g,h===a));h=h.nextSibling);b[E]=e}return f=a.sizset-d,0===c?0===f:0===f%c&&0<=f/c}}return function(b){var c=b;switch(a){case "only":case "first":for(;c=c.previousSibling;)if(1===c.nodeType)return!1;if("first"===a)return!0;c=b;case "last":for(;c=c.nextSibling;)if(1===c.nodeType)return!1;return!0}}},PSEUDO:function(a,b,c,e){var f,g=s.pseudos[a]||s.pseudos[a.toLowerCase()];return g||d.error("unsupported pseudo: "+a),g[E]?g(b,c,e):1<g.length?
(f=[a,a,"",b],function(a){return g(a,0,f)}):g}},pseudos:{not:Z(function(a,b,c){var d=q(a.replace(D,"$1"),b,c);return function(a){return!d(a)}}),enabled:function(a){return!1===a.disabled},disabled:function(a){return!0===a.disabled},checked:function(a){var b=a.nodeName.toLowerCase();return"input"===b&&!!a.checked||"option"===b&&!!a.selected},selected:function(a){return a.parentNode&&a.parentNode.selectedIndex,!0===a.selected},parent:function(a){return!s.pseudos.empty(a)},empty:function(a){for(var b,
a=a.firstChild;a;){if("@"<a.nodeName||3===(b=a.nodeType)||4===b)return!1;a=a.nextSibling}return!0},contains:Z(function(a){return function(b){return-1<(b.textContent||b.innerText||B(b)).indexOf(a)}}),has:Z(function(a){return function(b){return 0<d(a,b).length}}),header:function(a){return Q.test(a.nodeName)},text:function(a){var b,c;return"input"===a.nodeName.toLowerCase()&&"text"===(b=a.type)&&(null==(c=a.getAttribute("type"))||c.toLowerCase()===b)},radio:e("radio"),checkbox:e("checkbox"),file:e("file"),
password:e("password"),image:e("image"),submit:f("submit"),reset:f("reset"),button:function(a){var b=a.nodeName.toLowerCase();return"input"===b&&"button"===a.type||"button"===b},input:function(a){return R.test(a.nodeName)},focus:function(a){var b=a.ownerDocument;return a===b.activeElement&&(!b.hasFocus||b.hasFocus())&&(!!a.type||!!a.href)},active:function(a){return a===a.ownerDocument.activeElement}},setFilters:{first:function(a,b,c){return c?a.slice(1):[a[0]]},last:function(a,b,c){b=a.pop();return c?
a:[b]},even:function(a,b,c){for(var b=[],c=c?1:0,d=a.length;c<d;c+=2)b.push(a[c]);return b},odd:function(a,b,c){for(var b=[],c=c?0:1,d=a.length;c<d;c+=2)b.push(a[c]);return b},lt:function(a,b,c){return c?a.slice(+b):a.slice(0,+b)},gt:function(a,b,c){return c?a.slice(0,+b+1):a.slice(+b+1)},eq:function(a,b,c){b=a.splice(+b,1);return c?a:b}}};I=M.compareDocumentPosition?function(a,b){return a===b?(u=!0,0):(!a.compareDocumentPosition||!b.compareDocumentPosition?a.compareDocumentPosition:a.compareDocumentPosition(b)&
4)?-1:1}:function(a,b){if(a===b)return u=!0,0;if(a.sourceIndex&&b.sourceIndex)return a.sourceIndex-b.sourceIndex;var c,d,e=[],f=[];c=a.parentNode;d=b.parentNode;var h=c;if(c===d)return g(a,b);if(!c)return-1;if(!d)return 1;for(;h;)e.unshift(h),h=h.parentNode;for(h=d;h;)f.unshift(h),h=h.parentNode;c=e.length;d=f.length;for(h=0;h<c&&h<d;h++)if(e[h]!==f[h])return g(e[h],f[h]);return h===c?g(a,f[h],-1):g(e[h],b,1)};[0,0].sort(I);L=!u;d.uniqueSort=function(a){var b,c=1;u=L;a.sort(I);if(u)for(;b=a[c];c++)b===
a[c-1]&&a.splice(c--,1);return a};d.error=function(a){throw Error("Syntax error, unrecognized expression: "+a);};q=d.compile=function(a,b,c){var d,e,f,g=F[E][a];if(g&&g.context===b)return g;d=h(a,b,c);e=0;for(f=d.length;e<f;e++){for(var l=d,n=e,p=d[e],m=b,o=c,q=void 0,v=void 0,L=0;q=p[L];L++)s.relative[q.part]?v=i(v,s.relative[q.part],m,o):v=j(v,s.filter[q.part].apply(null,q.captures.concat(m,o)));l[n]=v}return g=F(a,k(d)),g.context=b,g.runs=g.dirruns=0,g};J.querySelectorAll&&function(){var a,b=o,
c=/'|\\/g,e=/\=[\x20\t\r\n\f]*([^'"\]]*)[\x20\t\r\n\f]*\]/g,f=[],g=[":active"],i=M.matchesSelector||M.mozMatchesSelector||M.webkitMatchesSelector||M.oMatchesSelector||M.msMatchesSelector;T(function(a){a.innerHTML="<select><option selected=''></option></select>";a.querySelectorAll("[selected]").length||f.push("\\["+w+"*(?:checked|disabled|ismap|multiple|readonly|selected|value)");a.querySelectorAll(":checked").length||f.push(":checked")});T(function(a){a.innerHTML="<p test=''></p>";a.querySelectorAll("[test^='']").length&&
f.push("[*^$]="+w+"*(?:\"\"|'')");a.innerHTML="<input type='hidden'/>";a.querySelectorAll(":enabled").length||f.push(":enabled",":disabled")});f=f.length&&RegExp(f.join("|"));o=function(a,d,e,g,i){if(!g&&!i&&(!f||!f.test(a)))if(9===d.nodeType)try{return X.apply(e,K.call(d.querySelectorAll(a),0)),e}catch(j){}else if(1===d.nodeType&&"object"!==d.nodeName.toLowerCase()){var k,l,n,p=d.getAttribute("id"),m=p||E,o=H.test(a)&&d.parentNode||d;p?m=m.replace(c,"\\$&"):d.setAttribute("id",m);k=h(a,d,i);m="[id='"+
m+"']";l=0;for(n=k.length;l<n;l++)k[l]=m+k[l].selector;try{return X.apply(e,K.call(o.querySelectorAll(k.join(",")),0)),e}catch(q){}finally{p||d.removeAttribute("id")}}return b(a,d,e,g,i)};i&&(T(function(b){a=i.call(b,"div");try{i.call(b,"[test!='']:sizzle"),g.push(S.PSEUDO.source,S.POS.source,"!=")}catch(c){}}),g=RegExp(g.join("|")),d.matchesSelector=function(b,c){c=c.replace(e,"='$1']");if(!ja(b)&&!g.test(c)&&(!f||!f.test(c)))try{var h=i.call(b,c);if(h||a||b.document&&11!==b.document.nodeType)return h}catch(j){}return 0<
d(c,null,null,[b]).length})}();s.setFilters.nth=s.setFilters.eq;s.filters=s.pseudos;d.attr=c.attr;c.find=d;c.expr=d.selectors;c.expr[":"]=c.expr.pseudos;c.unique=d.uniqueSort;c.text=d.getText;c.isXMLDoc=d.isXML;c.contains=d.contains})(o);var bc=/Until$/,cc=/^(?:parents|prev(?:Until|All))/,Ab=/^.[^:#\[\.,]*$/,jb=c.expr.match.needsContext,dc={children:!0,contents:!0,next:!0,prev:!0};c.fn.extend({find:function(a){var b,d,e,f,g,h,i=this;if("string"!=typeof a)return c(a).filter(function(){b=0;for(d=i.length;b<
d;b++)if(c.contains(i[b],this))return!0});h=this.pushStack("","find",a);b=0;for(d=this.length;b<d;b++)if(e=h.length,c.find(a,this[b],h),0<b)for(f=e;f<h.length;f++)for(g=0;g<e;g++)if(h[g]===h[f]){h.splice(f--,1);break}return h},has:function(a){var b,d=c(a,this),e=d.length;return this.filter(function(){for(b=0;b<e;b++)if(c.contains(this,d[b]))return!0})},not:function(a){return this.pushStack(Aa(this,a,!1),"not",a)},filter:function(a){return this.pushStack(Aa(this,a,!0),"filter",a)},is:function(a){return!!a&&
("string"==typeof a?jb.test(a)?0<=c(a,this.context).index(this[0]):0<c.filter(a,this).length:0<this.filter(a).length)},closest:function(a,b){for(var d,e=0,f=this.length,g=[],h=jb.test(a)||"string"!=typeof a?c(a,b||this.context):0;e<f;e++)for(d=this[e];d&&d.ownerDocument&&d!==b&&11!==d.nodeType;){if(h?-1<h.index(d):c.find.matchesSelector(d,a)){g.push(d);break}d=d.parentNode}return g=1<g.length?c.unique(g):g,this.pushStack(g,"closest",a)},index:function(a){return a?"string"==typeof a?c.inArray(this[0],
c(a)):c.inArray(a.jquery?a[0]:a,this):this[0]&&this[0].parentNode?this.prevAll().length:-1},add:function(a,b){var d="string"==typeof a?c(a,b):c.makeArray(a&&a.nodeType?[a]:a),e=c.merge(this.get(),d);return this.pushStack(P(d[0])||P(e[0])?e:c.unique(e))},addBack:function(a){return this.add(null==a?this.prevObject:this.prevObject.filter(a))}});c.fn.andSelf=c.fn.addBack;c.each({parent:function(a){return(a=a.parentNode)&&11!==a.nodeType?a:null},parents:function(a){return c.dir(a,"parentNode")},parentsUntil:function(a,
b,d){return c.dir(a,"parentNode",d)},next:function(a){return za(a,"nextSibling")},prev:function(a){return za(a,"previousSibling")},nextAll:function(a){return c.dir(a,"nextSibling")},prevAll:function(a){return c.dir(a,"previousSibling")},nextUntil:function(a,b,d){return c.dir(a,"nextSibling",d)},prevUntil:function(a,b,d){return c.dir(a,"previousSibling",d)},siblings:function(a){return c.sibling((a.parentNode||{}).firstChild,a)},children:function(a){return c.sibling(a.firstChild)},contents:function(a){return c.nodeName(a,
"iframe")?a.contentDocument||a.contentWindow.document:c.merge([],a.childNodes)}},function(a,b){c.fn[a]=function(d,e){var f=c.map(this,b,d);return bc.test(a)||(e=d),e&&"string"==typeof e&&(f=c.filter(e,f)),f=1<this.length&&!dc[a]?c.unique(f):f,1<this.length&&cc.test(a)&&(f=f.reverse()),this.pushStack(f,a,C.call(arguments).join(","))}});c.extend({filter:function(a,b,d){return d&&(a=":not("+a+")"),1===b.length?c.find.matchesSelector(b[0],a)?[b[0]]:[]:c.find.matches(a,b)},dir:function(a,b,d){for(var e=
[],a=a[b];a&&9!==a.nodeType&&(d===n||1!==a.nodeType||!c(a).is(d));)1===a.nodeType&&e.push(a),a=a[b];return e},sibling:function(a,b){for(var c=[];a;a=a.nextSibling)1===a.nodeType&&a!==b&&c.push(a);return c}});var Ca="abbr|article|aside|audio|bdi|canvas|data|datalist|details|figcaption|figure|footer|header|hgroup|mark|meter|nav|output|progress|section|summary|time|video",ec=/ jQuery\d+="(?:null|\d+)"/g,ta=/^\s+/,kb=/<(?!area|br|col|embed|hr|img|input|link|meta|param)(([\w:]+)[^>]*)\/>/gi,lb=/<([\w:]+)/,
fc=/<tbody/i,gc=/<|&#?\w+;/,hc=/<(?:script|style|link)/i,ic=/<(?:script|object|embed|option|style)/i,ua=RegExp("<(?:"+Ca+")[\\s/>]","i"),Fa=/^(?:checkbox|radio)$/,mb=/checked\s*(?:[^=]|=\s*.checked.)/i,jc=/\/(java|ecma)script/i,kc=/^\s*<!(?:\[CDATA\[|\-\-)|[\]\-]{2}>\s*$/g,x={option:[1,"<select multiple='multiple'>","</select>"],legend:[1,"<fieldset>","</fieldset>"],thead:[1,"<table>","</table>"],tr:[2,"<table><tbody>","</tbody></table>"],td:[3,"<table><tbody><tr>","</tr></tbody></table>"],col:[2,
"<table><tbody></tbody><colgroup>","</colgroup></table>"],area:[1,"<map>","</map>"],_default:[0,"",""]},nb=Ba(m),va=nb.appendChild(m.createElement("div"));x.optgroup=x.option;x.tbody=x.tfoot=x.colgroup=x.caption=x.thead;x.th=x.td;c.support.htmlSerialize||(x._default=[1,"X<div>","</div>"]);c.fn.extend({text:function(a){return c.access(this,function(a){return a===n?c.text(this):this.empty().append((this[0]&&this[0].ownerDocument||m).createTextNode(a))},null,a,arguments.length)},wrapAll:function(a){if(c.isFunction(a))return this.each(function(b){c(this).wrapAll(a.call(this,
b))});if(this[0]){var b=c(a,this[0].ownerDocument).eq(0).clone(!0);this[0].parentNode&&b.insertBefore(this[0]);b.map(function(){for(var a=this;a.firstChild&&1===a.firstChild.nodeType;)a=a.firstChild;return a}).append(this)}return this},wrapInner:function(a){return c.isFunction(a)?this.each(function(b){c(this).wrapInner(a.call(this,b))}):this.each(function(){var b=c(this),d=b.contents();d.length?d.wrapAll(a):b.append(a)})},wrap:function(a){var b=c.isFunction(a);return this.each(function(d){c(this).wrapAll(b?
a.call(this,d):a)})},unwrap:function(){return this.parent().each(function(){c.nodeName(this,"body")||c(this).replaceWith(this.childNodes)}).end()},append:function(){return this.domManip(arguments,!0,function(a){(this.nodeType===1||this.nodeType===11)&&this.appendChild(a)})},prepend:function(){return this.domManip(arguments,!0,function(a){(this.nodeType===1||this.nodeType===11)&&this.insertBefore(a,this.firstChild)})},before:function(){if(!P(this[0]))return this.domManip(arguments,!1,function(a){this.parentNode.insertBefore(a,
this)});if(arguments.length){var a=c.clean(arguments);return this.pushStack(c.merge(a,this),"before",this.selector)}},after:function(){if(!P(this[0]))return this.domManip(arguments,!1,function(a){this.parentNode.insertBefore(a,this.nextSibling)});if(arguments.length){var a=c.clean(arguments);return this.pushStack(c.merge(this,a),"after",this.selector)}},remove:function(a,b){for(var d,e=0;null!=(d=this[e]);e++)if(!a||c.filter(a,[d]).length)!b&&1===d.nodeType&&(c.cleanData(d.getElementsByTagName("*")),
c.cleanData([d])),d.parentNode&&d.parentNode.removeChild(d);return this},empty:function(){for(var a,b=0;null!=(a=this[b]);b++)for(1===a.nodeType&&c.cleanData(a.getElementsByTagName("*"));a.firstChild;)a.removeChild(a.firstChild);return this},clone:function(a,b){return a=null==a?!1:a,b=null==b?a:b,this.map(function(){return c.clone(this,a,b)})},html:function(a){return c.access(this,function(a){var d=this[0]||{},e=0,f=this.length;if(a===n)return 1===d.nodeType?d.innerHTML.replace(ec,""):n;if("string"==
typeof a&&!hc.test(a)&&(c.support.htmlSerialize||!ua.test(a))&&(c.support.leadingWhitespace||!ta.test(a))&&!x[(lb.exec(a)||["",""])[1].toLowerCase()]){a=a.replace(kb,"<$1></$2>");try{for(;e<f;e++)d=this[e]||{},1===d.nodeType&&(c.cleanData(d.getElementsByTagName("*")),d.innerHTML=a);d=0}catch(g){}}d&&this.empty().append(a)},null,a,arguments.length)},replaceWith:function(a){return P(this[0])?this.length?this.pushStack(c(c.isFunction(a)?a():a),"replaceWith",a):this:c.isFunction(a)?this.each(function(b){var d=
c(this),e=d.html();d.replaceWith(a.call(this,b,e))}):("string"!=typeof a&&(a=c(a).detach()),this.each(function(){var b=this.nextSibling,d=this.parentNode;c(this).remove();b?c(b).before(a):c(d).append(a)}))},detach:function(a){return this.remove(a,!0)},domManip:function(a,b,d){var a=[].concat.apply([],a),e,f,g,h=0,i=a[0],j=[],k=this.length;if(!c.support.checkClone&&1<k&&"string"==typeof i&&mb.test(i))return this.each(function(){c(this).domManip(a,b,d)});if(c.isFunction(i))return this.each(function(e){var f=
c(this);a[0]=i.call(this,e,b?f.html():n);f.domManip(a,b,d)});if(this[0]){e=c.buildFragment(a,this,j);g=e.fragment;f=g.firstChild;1===g.childNodes.length&&(g=f);if(f){b=b&&c.nodeName(f,"tr");for(e=e.cacheable||k-1;h<k;h++)d.call(b&&c.nodeName(this[h],"table")?this[h].getElementsByTagName("tbody")[0]||this[h].appendChild(this[h].ownerDocument.createElement("tbody")):this[h],h===e?g:c.clone(g,!0,!0))}g=f=null;j.length&&c.each(j,function(a,b){b.src?c.ajax?c.ajax({url:b.src,type:"GET",dataType:"script",
async:!1,global:!1,"throws":!0}):c.error("no ajax"):c.globalEval((b.text||b.textContent||b.innerHTML||"").replace(kc,""));b.parentNode&&b.parentNode.removeChild(b)})}return this}});c.buildFragment=function(a,b,d){var e,f,g,h=a[0];return b=b||m,b=!b.nodeType&&b[0]||b,b=b.ownerDocument||b,1===a.length&&"string"==typeof h&&512>h.length&&b===m&&"<"===h.charAt(0)&&!ic.test(h)&&(c.support.checkClone||!mb.test(h))&&(c.support.html5Clone||!ua.test(h))&&(f=!0,e=c.fragments[h],g=e!==n),e||(e=b.createDocumentFragment(),
c.clean(a,b,e,d),f&&(c.fragments[h]=g&&e)),{fragment:e,cacheable:f}};c.fragments={};c.each({appendTo:"append",prependTo:"prepend",insertBefore:"before",insertAfter:"after",replaceAll:"replaceWith"},function(a,b){c.fn[a]=function(d){var e,f=0,g=[],d=c(d),h=d.length;e=1===this.length&&this[0].parentNode;if((null==e||e&&11===e.nodeType&&1===e.childNodes.length)&&1===h)return d[b](this[0]),this;for(;f<h;f++)e=(0<f?this.clone(!0):this).get(),c(d[f])[b](e),g=g.concat(e);return this.pushStack(g,a,d.selector)}});
c.extend({clone:function(a,b,d){var e,f,g,h;c.support.html5Clone||c.isXMLDoc(a)||!ua.test("<"+a.nodeName+">")?h=a.cloneNode(!0):(va.innerHTML=a.outerHTML,va.removeChild(h=va.firstChild));if((!c.support.noCloneEvent||!c.support.noCloneChecked)&&(1===a.nodeType||11===a.nodeType)&&!c.isXMLDoc(a)){Ea(a,h);e=$(a);f=$(h);for(g=0;e[g];++g)f[g]&&Ea(e[g],f[g])}if(b&&(Da(a,h),d)){e=$(a);f=$(h);for(g=0;e[g];++g)Da(e[g],f[g])}return h},clean:function(a,b,d,e){var f,g,h,i,j,k,n,l=b===m&&nb,o=[];if(!b||"undefined"==
typeof b.createDocumentFragment)b=m;for(f=0;null!=(h=a[f]);f++)if("number"==typeof h&&(h+=""),h){if("string"==typeof h)if(gc.test(h)){l=l||Ba(b);k=b.createElement("div");l.appendChild(k);h=h.replace(kb,"<$1></$2>");g=(lb.exec(h)||["",""])[1].toLowerCase();i=x[g]||x._default;j=i[0];for(k.innerHTML=i[1]+h+i[2];j--;)k=k.lastChild;if(!c.support.tbody){j=fc.test(h);i="table"===g&&!j?k.firstChild&&k.firstChild.childNodes:"<table>"===i[1]&&!j?k.childNodes:[];for(g=i.length-1;0<=g;--g)c.nodeName(i[g],"tbody")&&
!i[g].childNodes.length&&i[g].parentNode.removeChild(i[g])}!c.support.leadingWhitespace&&ta.test(h)&&k.insertBefore(b.createTextNode(ta.exec(h)[0]),k.firstChild);h=k.childNodes;k.parentNode.removeChild(k)}else h=b.createTextNode(h);h.nodeType?o.push(h):c.merge(o,h)}k&&(h=k=l=null);if(!c.support.appendChecked)for(f=0;null!=(h=o[f]);f++)c.nodeName(h,"input")?Ga(h):"undefined"!=typeof h.getElementsByTagName&&c.grep(h.getElementsByTagName("input"),Ga);if(d){a=function(a){if(!a.type||jc.test(a.type))return e?
e.push(a.parentNode?a.parentNode.removeChild(a):a):d.appendChild(a)};for(f=0;null!=(h=o[f]);f++)if(!c.nodeName(h,"script")||!a(h))d.appendChild(h),"undefined"!=typeof h.getElementsByTagName&&(n=c.grep(c.merge([],h.getElementsByTagName("script")),a),o.splice.apply(o,[f+1,0].concat(n)),f+=n.length)}return o},cleanData:function(a,b){for(var d,e,f,g,h=0,i=c.expando,j=c.cache,k=c.support.deleteExpando,n=c.event.special;null!=(f=a[h]);h++)if(b||c.acceptData(f))if(d=(e=f[i])&&j[e]){if(d.events)for(g in d.events)n[g]?
c.event.remove(f,g):c.removeEvent(f,g,d.handle);j[e]&&(delete j[e],k?delete f[i]:f.removeAttribute?f.removeAttribute(i):f[i]=null,c.deletedIds.push(e))}}});(function(){var a,b;c.uaMatch=function(a){a=a.toLowerCase();a=/(chrome)[ \/]([\w.]+)/.exec(a)||/(webkit)[ \/]([\w.]+)/.exec(a)||/(opera)(?:.*version|)[ \/]([\w.]+)/.exec(a)||/(msie) ([\w.]+)/.exec(a)||0>a.indexOf("compatible")&&/(mozilla)(?:.*? rv:([\w.]+)|)/.exec(a)||[];return{browser:a[1]||"",version:a[2]||"0"}};a=c.uaMatch(Gb.userAgent);b={};
a.browser&&(b[a.browser]=!0,b.version=a.version);b.chrome?b.webkit=!0:b.webkit&&(b.safari=!0);c.browser=b;c.sub=function(){function a(b,c){return new a.fn.init(b,c)}c.extend(!0,a,this);a.superclass=this;a.fn=a.prototype=this();a.fn.constructor=a;a.sub=this.sub;a.fn.init=function(f,g){return g&&g instanceof c&&!(g instanceof a)&&(g=a(g)),c.fn.init.call(this,f,g,b)};a.fn.init.prototype=a.fn;var b=a(m);return a}})();var r,Q,R,wa=/alpha\([^)]*\)/i,lc=/opacity=([^)]*)/,mc=/^(top|right|bottom|left)$/,nc=
/^(none|table(?!-c[ea]).+)/,ob=/^margin/,Bb=RegExp("^("+ha+")(.*)$","i"),ba=RegExp("^("+ha+")(?!px)[a-z%]+$","i"),oc=RegExp("^([-+])=("+ha+")","i"),ma={},pc={position:"absolute",visibility:"hidden",display:"block"},pb={letterSpacing:0,fontWeight:400},N=["Top","Right","Bottom","Left"],Ia=["Webkit","O","Moz","ms"],qc=c.fn.toggle;c.fn.extend({css:function(a,b){return c.access(this,function(a,b,f){return f!==n?c.style(a,b,f):c.css(a,b)},a,b,1<arguments.length)},show:function(){return Ja(this,!0)},hide:function(){return Ja(this)},
toggle:function(a,b){var d="boolean"==typeof a;return c.isFunction(a)&&c.isFunction(b)?qc.apply(this,arguments):this.each(function(){(d?a:aa(this))?c(this).show():c(this).hide()})}});c.extend({cssHooks:{opacity:{get:function(a,b){if(b){var c=r(a,"opacity");return""===c?"1":c}}}},cssNumber:{fillOpacity:!0,fontWeight:!0,lineHeight:!0,opacity:!0,orphans:!0,widows:!0,zIndex:!0,zoom:!0},cssProps:{"float":c.support.cssFloat?"cssFloat":"styleFloat"},style:function(a,b,d,e){if(a&&!(3===a.nodeType||8===a.nodeType||
!a.style)){var f,g,h,i=c.camelCase(b),j=a.style,b=c.cssProps[i]||(c.cssProps[i]=Ha(j,i));h=c.cssHooks[b]||c.cssHooks[i];if(d===n)return h&&"get"in h&&(f=h.get(a,!1,e))!==n?f:j[b];g=typeof d;"string"===g&&(f=oc.exec(d))&&(d=(f[1]+1)*f[2]+parseFloat(c.css(a,b)),g="number");if(!(null==d||"number"===g&&isNaN(d)))if("number"===g&&!c.cssNumber[i]&&(d+="px"),!h||!("set"in h)||(d=h.set(a,d,e))!==n)try{j[b]=d}catch(k){}}},css:function(a,b,d,e){var f,g,h,i=c.camelCase(b);return b=c.cssProps[i]||(c.cssProps[i]=
Ha(a.style,i)),h=c.cssHooks[b]||c.cssHooks[i],h&&"get"in h&&(f=h.get(a,!0,e)),f===n&&(f=r(a,b)),"normal"===f&&b in pb&&(f=pb[b]),d||e!==n?(g=parseFloat(f),d||c.isNumeric(g)?g||0:f):f},swap:function(a,b,c){var e,f={};for(e in b)f[e]=a.style[e],a.style[e]=b[e];c=c.call(a);for(e in b)a.style[e]=f[e];return c}});o.getComputedStyle?r=function(a,b){var d,e,f,g,h=o.getComputedStyle(a,null),i=a.style;return h&&(d=h[b],""===d&&!c.contains(a.ownerDocument,a)&&(d=c.style(a,b)),ba.test(d)&&ob.test(b)&&(e=i.width,
f=i.minWidth,g=i.maxWidth,i.minWidth=i.maxWidth=i.width=d,d=h.width,i.width=e,i.minWidth=f,i.maxWidth=g)),d}:m.documentElement.currentStyle&&(r=function(a,b){var c,e,f=a.currentStyle&&a.currentStyle[b],g=a.style;return null==f&&g&&g[b]&&(f=g[b]),ba.test(f)&&!mc.test(b)&&(c=g.left,e=a.runtimeStyle&&a.runtimeStyle.left,e&&(a.runtimeStyle.left=a.currentStyle.left),g.left="fontSize"===b?"1em":f,f=g.pixelLeft+"px",g.left=c,e&&(a.runtimeStyle.left=e)),""===f?"auto":f});c.each(["height","width"],function(a,
b){c.cssHooks[b]={get:function(a,e,f){if(e)return 0===a.offsetWidth&&nc.test(r(a,"display"))?c.swap(a,pc,function(){return Na(a,b,f)}):Na(a,b,f)},set:function(a,e,f){return La(a,e,f?Ma(a,b,f,c.support.boxSizing&&"border-box"===c.css(a,"boxSizing")):0)}}});c.support.opacity||(c.cssHooks.opacity={get:function(a,b){return lc.test((b&&a.currentStyle?a.currentStyle.filter:a.style.filter)||"")?0.01*parseFloat(RegExp.$1)+"":b?"1":""},set:function(a,b){var d=a.style,e=a.currentStyle,f=c.isNumeric(b)?"alpha(opacity="+
100*b+")":"",g=e&&e.filter||d.filter||"";d.zoom=1;if(1<=b&&""===c.trim(g.replace(wa,""))&&d.removeAttribute&&(d.removeAttribute("filter"),e&&!e.filter))return;d.filter=wa.test(g)?g.replace(wa,f):g+" "+f}});c(function(){c.support.reliableMarginRight||(c.cssHooks.marginRight={get:function(a,b){return c.swap(a,{display:"inline-block"},function(){if(b)return r(a,"marginRight")})}});!c.support.pixelPosition&&c.fn.position&&c.each(["top","left"],function(a,b){c.cssHooks[b]={get:function(a,e){if(e){var f=
r(a,b);return ba.test(f)?c(a).position()[b]+"px":f}}}})});c.expr&&c.expr.filters&&(c.expr.filters.hidden=function(a){return 0===a.offsetWidth&&0===a.offsetHeight||!c.support.reliableHiddenOffsets&&"none"===(a.style&&a.style.display||r(a,"display"))},c.expr.filters.visible=function(a){return!c.expr.filters.hidden(a)});c.each({margin:"",padding:"",border:"Width"},function(a,b){c.cssHooks[a+b]={expand:function(c){for(var e="string"==typeof c?c.split(" "):[c],f={},c=0;4>c;c++)f[a+N[c]+b]=e[c]||e[c-2]||
e[0];return f}};ob.test(a)||(c.cssHooks[a+b].set=La)});var rc=/%20/g,Cb=/\[\]$/,qb=/\r?\n/g,sc=/^(?:color|date|datetime|datetime-local|email|hidden|month|number|password|range|search|tel|text|time|url|week)$/i,tc=/^(?:select|textarea)/i;c.fn.extend({serialize:function(){return c.param(this.serializeArray())},serializeArray:function(){return this.map(function(){return this.elements?c.makeArray(this.elements):this}).filter(function(){return this.name&&!this.disabled&&(this.checked||tc.test(this.nodeName)||
sc.test(this.type))}).map(function(a,b){var d=c(this).val();return null==d?null:c.isArray(d)?c.map(d,function(a){return{name:b.name,value:a.replace(qb,"\r\n")}}):{name:b.name,value:d.replace(qb,"\r\n")}}).get()}});c.param=function(a,b){var d,e=[],f=function(a,b){b=c.isFunction(b)?b():null==b?"":b;e[e.length]=encodeURIComponent(a)+"="+encodeURIComponent(b)};b===n&&(b=c.ajaxSettings&&c.ajaxSettings.traditional);if(c.isArray(a)||a.jquery&&!c.isPlainObject(a))c.each(a,function(){f(this.name,this.value)});
else for(d in a)na(d,a[d],b,f);return e.join("&").replace(rc,"+")};var H,O,uc=/#.*$/,vc=/^(.*?):[ \t]*([^\r\n]*)\r?$/mg,wc=/^(?:GET|HEAD)$/,xc=/^\/\//,rb=/\?/,yc=/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi,zc=/([?&])_=[^&]*/,sb=/^([\w\+\.\-]+:)(?:\/\/([^\/?#:]*)(?::(\d+)|)|)/,tb=c.fn.load,oa={},ub={},vb=["*/"]+["*"];try{H=Fb.href}catch(Gc){H=m.createElement("a"),H.href="",H=H.href}O=sb.exec(H.toLowerCase())||[];c.fn.load=function(a,b,d){if("string"!=typeof a&&tb)return tb.apply(this,arguments);
if(!this.length)return this;var e,f,g,h=this,i=a.indexOf(" ");return 0<=i&&(e=a.slice(i,a.length),a=a.slice(0,i)),c.isFunction(b)?(d=b,b=n):b&&"object"==typeof b&&(f="POST"),c.ajax({url:a,type:f,dataType:"html",data:b,complete:function(a,b){d&&h.each(d,g||[a.responseText,b,a])}}).done(function(a){g=arguments;h.html(e?c("<div>").append(a.replace(yc,"")).find(e):a)}),this};c.each("ajaxStart,ajaxStop,ajaxComplete,ajaxError,ajaxSuccess,ajaxSend".split(","),function(a,b){c.fn[b]=function(a){return this.on(b,
a)}});c.each(["get","post"],function(a,b){c[b]=function(a,e,f,g){return c.isFunction(e)&&(g=g||f,f=e,e=n),c.ajax({type:b,url:a,data:e,success:f,dataType:g})}});c.extend({getScript:function(a,b){return c.get(a,n,b,"script")},getJSON:function(a,b,d){return c.get(a,b,d,"json")},ajaxSetup:function(a,b){return b?Pa(a,c.ajaxSettings):(b=a,a=c.ajaxSettings),Pa(a,b),a},ajaxSettings:{url:H,isLocal:/^(?:about|app|app\-storage|.+\-extension|file|res|widget):$/.test(O[1]),global:!0,type:"GET",contentType:"application/x-www-form-urlencoded; charset=UTF-8",
processData:!0,async:!0,accepts:{xml:"application/xml, text/xml",html:"text/html",text:"text/plain",json:"application/json, text/javascript","*":vb},contents:{xml:/xml/,html:/html/,json:/json/},responseFields:{xml:"responseXML",text:"responseText"},converters:{"* text":o.String,"text html":!0,"text json":c.parseJSON,"text xml":c.parseXML},flatOptions:{context:!0,url:!0}},ajaxPrefilter:Oa(oa),ajaxTransport:Oa(ub),ajax:function(a,b){function d(a,b,d,g){var j,m,p,s,y,r=b;if(2!==x){x=2;i&&clearTimeout(i);
h=n;f=g||"";q.readyState=0<a?4:0;if(d){s=l;var g=q,u,F,w,C,D=s.contents,A=s.dataTypes,I=s.responseFields;for(F in I)F in d&&(g[I[F]]=d[F]);for(;"*"===A[0];)A.shift(),u===n&&(u=s.mimeType||g.getResponseHeader("content-type"));if(u)for(F in D)if(D[F]&&D[F].test(u)){A.unshift(F);break}if(A[0]in d)w=A[0];else{for(F in d){if(!A[0]||s.converters[F+" "+A[0]]){w=F;break}C||(C=F)}w=w||C}s=w?(w!==A[0]&&A.unshift(w),d[w]):void 0}if(200<=a&&300>a||304===a)if(l.ifModified&&(y=q.getResponseHeader("Last-Modified"),
y&&(c.lastModified[e]=y),y=q.getResponseHeader("Etag"),y&&(c.etag[e]=y)),304===a)r="notmodified",j=!0;else{var G;a:{d=l;j=s;var H;y=d.dataTypes.slice();r=y[0];u={};F=0;d.dataFilter&&(j=d.dataFilter(j,d.dataType));if(y[1])for(G in d.converters)u[G.toLowerCase()]=d.converters[G];for(;m=y[++F];)if("*"!==m){if("*"!==r&&r!==m){G=u[r+" "+m]||u["* "+m];if(!G)for(H in u)if(p=H.split(" "),p[1]===m&&(G=u[r+" "+p[0]]||u["* "+p[0]])){!0===G?G=u[H]:!0!==u[H]&&(m=p[0],y.splice(F--,0,m));break}if(!0!==G)if(G&&d["throws"])j=
G(j);else try{j=G(j)}catch(N){G={state:"parsererror",error:G?N:"No conversion from "+r+" to "+m};break a}}r=m}G={state:"success",data:j}}j=G;r=j.state;m=j.data;p=j.error;j=!p}else if(p=r,!r||a)r="error",0>a&&(a=0);q.status=a;q.statusText=""+(b||r);j?t.resolveWith(o,[m,r,q]):t.rejectWith(o,[q,r,p]);q.statusCode(z);z=n;k&&v.trigger("ajax"+(j?"Success":"Error"),[q,l,j?m:p]);B.fireWith(o,[q,r]);k&&(v.trigger("ajaxComplete",[q,l]),--c.active||c.event.trigger("ajaxStop"))}}"object"==typeof a&&(b=a,a=n);
var b=b||{},e,f,g,h,i,j,k,m,l=c.ajaxSetup({},b),o=l.context||l,v=o!==l&&(o.nodeType||o instanceof c)?c(o):c.event,t=c.Deferred(),B=c.Callbacks("once memory"),z=l.statusCode||{},s={},r={},x=0,u="canceled",q={readyState:0,setRequestHeader:function(a,b){if(!x){var c=a.toLowerCase(),a=r[c]=r[c]||a;s[a]=b}return this},getAllResponseHeaders:function(){return 2===x?f:null},getResponseHeader:function(a){var b;if(2===x){if(!g)for(g={};b=vc.exec(f);)g[b[1].toLowerCase()]=b[2];b=g[a.toLowerCase()]}return b===
n?null:b},overrideMimeType:function(a){return x||(l.mimeType=a),this},abort:function(a){return a=a||u,h&&h.abort(a),d(0,a),this}};t.promise(q);q.success=q.done;q.error=q.fail;q.complete=B.add;q.statusCode=function(a){if(a){var b;if(2>x)for(b in a)z[b]=[z[b],a[b]];else b=a[q.status],q.always(b)}return this};l.url=((a||l.url)+"").replace(uc,"").replace(xc,O[1]+"//");l.dataTypes=c.trim(l.dataType||"*").toLowerCase().split(A);null==l.crossDomain&&(j=sb.exec(l.url.toLowerCase()),l.crossDomain=!(!j||j[1]==
O[1]&&j[2]==O[2]&&(j[3]||("http:"===j[1]?80:443))==(O[3]||("http:"===O[1]?80:443))));l.data&&l.processData&&"string"!=typeof l.data&&(l.data=c.param(l.data,l.traditional));ca(oa,l,b,q);if(2===x)return q;k=l.global;l.type=l.type.toUpperCase();l.hasContent=!wc.test(l.type);k&&0===c.active++&&c.event.trigger("ajaxStart");if(!l.hasContent&&(l.data&&(l.url+=(rb.test(l.url)?"&":"?")+l.data,delete l.data),e=l.url,!1===l.cache)){j=c.now();var C=l.url.replace(zc,"$1_="+j);l.url=C+(C===l.url?(rb.test(l.url)?
"&":"?")+"_="+j:"")}(l.data&&l.hasContent&&!1!==l.contentType||b.contentType)&&q.setRequestHeader("Content-Type",l.contentType);l.ifModified&&(e=e||l.url,c.lastModified[e]&&q.setRequestHeader("If-Modified-Since",c.lastModified[e]),c.etag[e]&&q.setRequestHeader("If-None-Match",c.etag[e]));q.setRequestHeader("Accept",l.dataTypes[0]&&l.accepts[l.dataTypes[0]]?l.accepts[l.dataTypes[0]]+("*"!==l.dataTypes[0]?", "+vb+"; q=0.01":""):l.accepts["*"]);for(m in l.headers)q.setRequestHeader(m,l.headers[m]);if(!l.beforeSend||
!1!==l.beforeSend.call(o,q,l)&&2!==x){u="abort";for(m in{success:1,error:1,complete:1})q[m](l[m]);if(h=ca(ub,l,b,q)){q.readyState=1;k&&v.trigger("ajaxSend",[q,l]);l.async&&0<l.timeout&&(i=setTimeout(function(){q.abort("timeout")},l.timeout));try{x=1,h.send(s,d)}catch(D){if(2>x)d(-1,D);else throw D;}}else d(-1,"No Transport");return q}return q.abort()},active:0,lastModified:{},etag:{}});var wb=[],Ac=/\?/,ka=/(=)\?(?=&|$)|\?\?/,Bc=c.now();c.ajaxSetup({jsonp:"callback",jsonpCallback:function(){var a=
wb.pop()||c.expando+"_"+Bc++;return this[a]=!0,a}});c.ajaxPrefilter("json jsonp",function(a,b,d){var e,f,g,h=a.data,i=a.url,j=!1!==a.jsonp,k=j&&ka.test(i),m=j&&!k&&"string"==typeof h&&!(a.contentType||"").indexOf("application/x-www-form-urlencoded")&&ka.test(h);if("jsonp"===a.dataTypes[0]||k||m)return e=a.jsonpCallback=c.isFunction(a.jsonpCallback)?a.jsonpCallback():a.jsonpCallback,f=o[e],k?a.url=i.replace(ka,"$1"+e):m?a.data=h.replace(ka,"$1"+e):j&&(a.url+=(Ac.test(i)?"&":"?")+a.jsonp+"="+e),a.converters["script json"]=
function(){return g||c.error(e+" was not called"),g[0]},a.dataTypes[0]="json",o[e]=function(){g=arguments},d.always(function(){o[e]=f;a[e]&&(a.jsonpCallback=b.jsonpCallback,wb.push(e));g&&c.isFunction(f)&&f(g[0]);g=f=n}),"script"});c.ajaxSetup({accepts:{script:"text/javascript, application/javascript, application/ecmascript, application/x-ecmascript"},contents:{script:/javascript|ecmascript/},converters:{"text script":function(a){return c.globalEval(a),a}}});c.ajaxPrefilter("script",function(a){a.cache===
n&&(a.cache=!1);a.crossDomain&&(a.type="GET",a.global=!1)});c.ajaxTransport("script",function(a){if(a.crossDomain){var b,c=m.head||m.getElementsByTagName("head")[0]||m.documentElement;return{send:function(e,f){b=m.createElement("script");b.async="async";a.scriptCharset&&(b.charset=a.scriptCharset);b.src=a.url;b.onload=b.onreadystatechange=function(a,e){if(e||!b.readyState||/loaded|complete/.test(b.readyState))b.onload=b.onreadystatechange=null,c&&b.parentNode&&c.removeChild(b),b=n,e||f(200,"success")};
c.insertBefore(b,c.firstChild)},abort:function(){b&&b.onload(0,1)}}}});var U,xa=o.ActiveXObject?function(){for(var a in U)U[a](0,1)}:!1,Cc=0;c.ajaxSettings.xhr=o.ActiveXObject?function(){var a;if(!(a=!this.isLocal&&Qa()))a:{try{a=new o.ActiveXObject("Microsoft.XMLHTTP");break a}catch(b){}a=void 0}return a}:Qa;(function(a){c.extend(c.support,{ajax:!!a,cors:!!a&&"withCredentials"in a})})(c.ajaxSettings.xhr());c.support.ajax&&c.ajaxTransport(function(a){if(!a.crossDomain||c.support.cors){var b;return{send:function(d,
e){var f,g,h=a.xhr();a.username?h.open(a.type,a.url,a.async,a.username,a.password):h.open(a.type,a.url,a.async);if(a.xhrFields)for(g in a.xhrFields)h[g]=a.xhrFields[g];a.mimeType&&h.overrideMimeType&&h.overrideMimeType(a.mimeType);!a.crossDomain&&!d["X-Requested-With"]&&(d["X-Requested-With"]="XMLHttpRequest");try{for(g in d)h.setRequestHeader(g,d[g])}catch(i){}h.send(a.hasContent&&a.data||null);b=function(d,g){var i,l,m,o,r;try{if(b&&(g||4===h.readyState))if(b=n,f&&(h.onreadystatechange=c.noop,xa&&
delete U[f]),g)4!==h.readyState&&h.abort();else{i=h.status;m=h.getAllResponseHeaders();o={};(r=h.responseXML)&&r.documentElement&&(o.xml=r);try{o.text=h.responseText}catch(t){}try{l=h.statusText}catch(u){l=""}!i&&a.isLocal&&!a.crossDomain?i=o.text?200:404:1223===i&&(i=204)}}catch(s){g||e(-1,s)}o&&e(i,l,o,m)};a.async?4===h.readyState?setTimeout(b,0):(f=++Cc,xa&&(U||(U={},c(o).unload(xa)),U[f]=b),h.onreadystatechange=b):b()},abort:function(){b&&b(0,1)}}}});var da,la,Dc=/^(?:toggle|show|hide)$/,Ec=RegExp("^(?:([-+])=|)("+
ha+")([a-z%]*)$","i"),Fc=/queueHooks$/,ea=[function(a,b,d){var e,f,g,h,i,j,k=this,m=a.style,l={},n=[],o=a.nodeType&&aa(a);d.queue||(i=c._queueHooks(a,"fx"),null==i.unqueued&&(i.unqueued=0,j=i.empty.fire,i.empty.fire=function(){i.unqueued||j()}),i.unqueued++,k.always(function(){k.always(function(){i.unqueued--;c.queue(a,"fx").length||i.empty.fire()})}));1===a.nodeType&&("height"in b||"width"in b)&&(d.overflow=[m.overflow,m.overflowX,m.overflowY],"inline"===c.css(a,"display")&&"none"===c.css(a,"float")&&
(!c.support.inlineBlockNeedsLayout||"inline"===Ka(a.nodeName)?m.display="inline-block":m.zoom=1));d.overflow&&(m.overflow="hidden",c.support.shrinkWrapBlocks||k.done(function(){m.overflow=d.overflow[0];m.overflowX=d.overflow[1];m.overflowY=d.overflow[2]}));for(e in b)f=b[e],Dc.exec(f)&&(delete b[e],f!==(o?"hide":"show")&&n.push(e));if(f=n.length){g=c._data(a,"fxshow")||c._data(a,"fxshow",{});o?c(a).show():k.done(function(){c(a).hide()});k.done(function(){var b;c.removeData(a,"fxshow",!0);for(b in l)c.style(a,
b,l[b])});for(e=0;e<f;e++)b=n[e],h=k.createTween(b,o?g[b]:0),l[b]=g[b]||c.style(a,b),b in g||(g[b]=h.start,o&&(h.end=h.start,h.start="width"===b||"height"===b?1:0))}}],V={"*":[function(a,b){var d,e,f,g=this.createTween(a,b),h=Ec.exec(b),i=g.cur(),j=+i||0,k=1;if(h){d=+h[2];e=h[3]||(c.cssNumber[a]?"":"px");if("px"!==e&&j){j=c.css(g.elem,a,!0)||d||1;do f=k=k||".5",j/=k,c.style(g.elem,a,j+e),k=g.cur()/i;while(1!==k&&k!==f)}g.unit=e;g.start=j;g.end=h[1]?j+(h[1]+1)*d:d}return g}]};c.Animation=c.extend(Sa,
{tweener:function(a,b){c.isFunction(a)?(b=a,a=["*"]):a=a.split(" ");for(var d,e=0,f=a.length;e<f;e++)d=a[e],V[d]=V[d]||[],V[d].unshift(b)},prefilter:function(a,b){b?ea.unshift(a):ea.push(a)}});c.Tween=B;B.prototype={constructor:B,init:function(a,b,d,e,f,g){this.elem=a;this.prop=d;this.easing=f||"swing";this.options=b;this.start=this.now=this.cur();this.end=e;this.unit=g||(c.cssNumber[d]?"":"px")},cur:function(){var a=B.propHooks[this.prop];return a&&a.get?a.get(this):B.propHooks._default.get(this)},
run:function(a){var b,d=B.propHooks[this.prop];return this.options.duration?this.pos=b=c.easing[this.easing](a,this.options.duration*a,0,1,this.options.duration):this.pos=b=a,this.now=(this.end-this.start)*b+this.start,this.options.step&&this.options.step.call(this.elem,this.now,this),d&&d.set?d.set(this):B.propHooks._default.set(this),this}};B.prototype.init.prototype=B.prototype;B.propHooks={_default:{get:function(a){var b;return null==a.elem[a.prop]||a.elem.style&&null!=a.elem.style[a.prop]?(b=
c.css(a.elem,a.prop,!1,""),!b||"auto"===b?0:b):a.elem[a.prop]},set:function(a){c.fx.step[a.prop]?c.fx.step[a.prop](a):a.elem.style&&(null!=a.elem.style[c.cssProps[a.prop]]||c.cssHooks[a.prop])?c.style(a.elem,a.prop,a.now+a.unit):a.elem[a.prop]=a.now}}};B.propHooks.scrollTop=B.propHooks.scrollLeft={set:function(a){a.elem.nodeType&&a.elem.parentNode&&(a.elem[a.prop]=a.now)}};c.each(["toggle","show","hide"],function(a,b){var d=c.fn[b];c.fn[b]=function(e,f,g){return null==e||"boolean"==typeof e||!a&&
c.isFunction(e)&&c.isFunction(f)?d.apply(this,arguments):this.animate(fa(b,!0),e,f,g)}});c.fn.extend({fadeTo:function(a,b,c,e){return this.filter(aa).css("opacity",0).show().end().animate({opacity:b},a,c,e)},animate:function(a,b,d,e){var f=c.isEmptyObject(a),g=c.speed(b,d,e),b=function(){var b=Sa(this,c.extend({},a),g);f&&b.stop(!0)};return f||!1===g.queue?this.each(b):this.queue(g.queue,b)},stop:function(a,b,d){var e=function(a){var b=a.stop;delete a.stop;b(d)};return"string"!=typeof a&&(d=b,b=a,
a=n),b&&!1!==a&&this.queue(a||"fx",[]),this.each(function(){var b=!0,g=null!=a&&a+"queueHooks",h=c.timers,i=c._data(this);if(g)i[g]&&i[g].stop&&e(i[g]);else for(g in i)i[g]&&i[g].stop&&Fc.test(g)&&e(i[g]);for(g=h.length;g--;)h[g].elem===this&&(null==a||h[g].queue===a)&&(h[g].anim.stop(d),b=!1,h.splice(g,1));(b||!d)&&c.dequeue(this,a)})}});c.each({slideDown:fa("show"),slideUp:fa("hide"),slideToggle:fa("toggle"),fadeIn:{opacity:"show"},fadeOut:{opacity:"hide"},fadeToggle:{opacity:"toggle"}},function(a,
b){c.fn[a]=function(a,c,f){return this.animate(b,a,c,f)}});c.speed=function(a,b,d){var e=a&&"object"==typeof a?c.extend({},a):{complete:d||!d&&b||c.isFunction(a)&&a,duration:a,easing:d&&b||b&&!c.isFunction(b)&&b};e.duration=c.fx.off?0:"number"==typeof e.duration?e.duration:e.duration in c.fx.speeds?c.fx.speeds[e.duration]:c.fx.speeds._default;if(null==e.queue||!0===e.queue)e.queue="fx";return e.old=e.complete,e.complete=function(){c.isFunction(e.old)&&e.old.call(this);e.queue&&c.dequeue(this,e.queue)},
e};c.easing={linear:function(a){return a},swing:function(a){return 0.5-Math.cos(a*Math.PI)/2}};c.timers=[];c.fx=B.prototype.init;c.fx.tick=function(){for(var a,b=c.timers,d=0;d<b.length;d++)a=b[d],!a()&&b[d]===a&&b.splice(d--,1);b.length||c.fx.stop()};c.fx.timer=function(a){a()&&c.timers.push(a)&&!la&&(la=setInterval(c.fx.tick,c.fx.interval))};c.fx.interval=13;c.fx.stop=function(){clearInterval(la);la=null};c.fx.speeds={slow:600,fast:200,_default:400};c.fx.step={};c.expr&&c.expr.filters&&(c.expr.filters.animated=
function(a){return c.grep(c.timers,function(b){return a===b.elem}).length});var xb=/^(?:body|html)$/i;c.fn.offset=function(a){if(arguments.length)return a===n?this:this.each(function(b){c.offset.setOffset(this,a,b)});var b,d,e,f,g,h,i,j,k,m,l=this[0],o=l&&l.ownerDocument;return!o?void 0:(e=o.body)===l?c.offset.bodyOffset(l):(d=o.documentElement,c.contains(d,l)?(b=l.getBoundingClientRect(),f=Ta(o),g=d.clientTop||e.clientTop||0,h=d.clientLeft||e.clientLeft||0,i=f.pageYOffset||d.scrollTop,j=f.pageXOffset||
d.scrollLeft,k=b.top+i-g,m=b.left+j-h,{top:k,left:m}):{top:0,left:0})};c.offset={bodyOffset:function(a){var b=a.offsetTop,d=a.offsetLeft;return c.support.doesNotIncludeMarginInBodyOffset&&(b+=parseFloat(c.css(a,"marginTop"))||0,d+=parseFloat(c.css(a,"marginLeft"))||0),{top:b,left:d}},setOffset:function(a,b,d){var e=c.css(a,"position");"static"===e&&(a.style.position="relative");var f=c(a),g=f.offset(),h=c.css(a,"top"),i=c.css(a,"left"),j={},k={},m,l;("absolute"===e||"fixed"===e)&&-1<c.inArray("auto",
[h,i])?(k=f.position(),m=k.top,l=k.left):(m=parseFloat(h)||0,l=parseFloat(i)||0);c.isFunction(b)&&(b=b.call(a,d,g));null!=b.top&&(j.top=b.top-g.top+m);null!=b.left&&(j.left=b.left-g.left+l);"using"in b?b.using.call(a,j):f.css(j)}};c.fn.extend({position:function(){if(this[0]){var a=this[0],b=this.offsetParent(),d=this.offset(),e=xb.test(b[0].nodeName)?{top:0,left:0}:b.offset();return d.top-=parseFloat(c.css(a,"marginTop"))||0,d.left-=parseFloat(c.css(a,"marginLeft"))||0,e.top+=parseFloat(c.css(b[0],
"borderTopWidth"))||0,e.left+=parseFloat(c.css(b[0],"borderLeftWidth"))||0,{top:d.top-e.top,left:d.left-e.left}}},offsetParent:function(){return this.map(function(){for(var a=this.offsetParent||m.body;a&&!xb.test(a.nodeName)&&"static"===c.css(a,"position");)a=a.offsetParent;return a||m.body})}});c.each({scrollLeft:"pageXOffset",scrollTop:"pageYOffset"},function(a,b){var d=/Y/.test(b);c.fn[a]=function(e){return c.access(this,function(a,e,h){var i=Ta(a);if(h===n)return i?b in i?i[b]:i.document.documentElement[e]:
a[e];i?i.scrollTo(d?c(i).scrollLeft():h,d?h:c(i).scrollTop()):a[e]=h},a,e,arguments.length,null)}});c.each({Height:"height",Width:"width"},function(a,b){c.each({padding:"inner"+a,content:b,"":"outer"+a},function(d,e){c.fn[e]=function(e,g){var h=arguments.length&&(d||"boolean"!=typeof e),i=d||(!0===e||!0===g?"margin":"border");return c.access(this,function(b,d,e){var f;return c.isWindow(b)?b.document.documentElement["client"+a]:9===b.nodeType?(f=b.documentElement,Math.max(b.body["scroll"+a],f["scroll"+
a],b.body["offset"+a],f["offset"+a],f["client"+a])):e===n?c.css(b,d,e,i):c.style(b,d,e,i)},b,h?e:n,h,null)}})});o.jQuery=o.$=c;"function"==typeof define&&define.amd&&define.amd.jQuery&&define("jquery",[],function(){return c})})(window);
jQuery.cookie=function(o,n,t){if("undefined"!=typeof n){t=t||{path:"/",domain:".17shangke.com"};null===n&&(n="",t.expires=-1);var z="";if(t.expires&&("number"==typeof t.expires||t.expires.toUTCString))"number"==typeof t.expires?(z=new Date,z.setTime(z.getTime()+864E5*t.expires)):z=t.expires,z="; expires="+z.toUTCString();var I=t.path?"; path="+t.path:"",u=t.domain?"; domain="+t.domain:"",t=t.secure?"; secure":"";document.cookie=[o,"=",encodeURIComponent(n),z,I,u,t].join("")}else{n=null;if(document.cookie&&
""!=document.cookie){t=document.cookie.split(";");for(z=0;z<t.length;z++)if(I=jQuery.trim(t[z]),I.substring(0,o.length+1)==o+"="){n=decodeURIComponent(I.substring(o.length+1));break}}return n}};
